/*
 * Generated by asn1c-v1.4-23-g5baed98c-2026-03-30 (https://github.com/mouse07410/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "../support/s1ap-r17.3.0/36413-h30.asn"
 * 	`asn1c -pdu=all -fprefix=S1AP_ -fcompound-names -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-CBOR -no-gen-OER -no-gen-UPER`
 */

#ifndef	_S1AP_BroadcastCompletedAreaList_H_
#define	_S1AP_BroadcastCompletedAreaList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum S1AP_BroadcastCompletedAreaList_PR {
	S1AP_BroadcastCompletedAreaList_PR_NOTHING,	/* No components present */
	S1AP_BroadcastCompletedAreaList_PR_cellID_Broadcast,
	S1AP_BroadcastCompletedAreaList_PR_tAI_Broadcast,
	S1AP_BroadcastCompletedAreaList_PR_emergencyAreaID_Broadcast
	/* Extensions may appear below */
	
} S1AP_BroadcastCompletedAreaList_PR;

/* Forward declarations */
struct S1AP_CellID_Broadcast;
struct S1AP_TAI_Broadcast;
struct S1AP_EmergencyAreaID_Broadcast;

/* S1AP_BroadcastCompletedAreaList */
typedef struct S1AP_BroadcastCompletedAreaList {
	S1AP_BroadcastCompletedAreaList_PR present;
	union S1AP_BroadcastCompletedAreaList_u {
		struct S1AP_CellID_Broadcast	*cellID_Broadcast;
		struct S1AP_TAI_Broadcast	*tAI_Broadcast;
		struct S1AP_EmergencyAreaID_Broadcast	*emergencyAreaID_Broadcast;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_BroadcastCompletedAreaList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_S1AP_BroadcastCompletedAreaList;
extern asn_CHOICE_specifics_t asn_SPC_S1AP_BroadcastCompletedAreaList_specs_1;
extern asn_TYPE_member_t asn_MBR_S1AP_BroadcastCompletedAreaList_1[3];
extern asn_per_constraints_t asn_PER_type_S1AP_BroadcastCompletedAreaList_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "S1AP_CellID-Broadcast.h"
#include "S1AP_TAI-Broadcast.h"
#include "S1AP_EmergencyAreaID-Broadcast.h"

#endif	/* _S1AP_BroadcastCompletedAreaList_H_ */
#include <asn_internal.h>
