/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "../support/s1ap-r16.1.0/36413-g10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#include "S1AP_BroadcastCancelledAreaList.h"

#include "S1AP_CellID-Cancelled.h"
#include "S1AP_TAI-Cancelled.h"
#include "S1AP_EmergencyAreaID-Cancelled.h"
static asn_oer_constraints_t asn_OER_type_S1AP_BroadcastCancelledAreaList_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_S1AP_BroadcastCancelledAreaList_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  2,  2,  0,  2 }	/* (0..2,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_S1AP_BroadcastCancelledAreaList_1[] = {
	{ ATF_POINTER, 0, offsetof(struct S1AP_BroadcastCancelledAreaList, choice.cellID_Cancelled),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_S1AP_CellID_Cancelled,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cellID-Cancelled"
		},
	{ ATF_POINTER, 0, offsetof(struct S1AP_BroadcastCancelledAreaList, choice.tAI_Cancelled),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_S1AP_TAI_Cancelled,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"tAI-Cancelled"
		},
	{ ATF_POINTER, 0, offsetof(struct S1AP_BroadcastCancelledAreaList, choice.emergencyAreaID_Cancelled),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_S1AP_EmergencyAreaID_Cancelled,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"emergencyAreaID-Cancelled"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_S1AP_BroadcastCancelledAreaList_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* cellID-Cancelled */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* tAI-Cancelled */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* emergencyAreaID-Cancelled */
};
static asn_CHOICE_specifics_t asn_SPC_S1AP_BroadcastCancelledAreaList_specs_1 = {
	sizeof(struct S1AP_BroadcastCancelledAreaList),
	offsetof(struct S1AP_BroadcastCancelledAreaList, _asn_ctx),
	offsetof(struct S1AP_BroadcastCancelledAreaList, present),
	sizeof(((struct S1AP_BroadcastCancelledAreaList *)0)->present),
	asn_MAP_S1AP_BroadcastCancelledAreaList_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0,
	3	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_S1AP_BroadcastCancelledAreaList = {
	"BroadcastCancelledAreaList",
	"BroadcastCancelledAreaList",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_S1AP_BroadcastCancelledAreaList_constr_1, &asn_PER_type_S1AP_BroadcastCancelledAreaList_constr_1, CHOICE_constraint },
	asn_MBR_S1AP_BroadcastCancelledAreaList_1,
	3,	/* Elements count */
	&asn_SPC_S1AP_BroadcastCancelledAreaList_specs_1	/* Additional specs */
};

