/*
 * Generated by asn1c-v1.4-23-g5baed98c-2026-03-30 (https://github.com/mouse07410/asn1c)
 * From ASN.1 module "S1AP-PDU-Contents"
 * 	found in "../support/s1ap-r17.3.0/36413-h30.asn"
 * 	`asn1c -pdu=all -fprefix=S1AP_ -fcompound-names -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-CBOR -no-gen-OER -no-gen-UPER`
 */

#include "S1AP_UEContextModificationFailure.h"

asn_TYPE_member_t asn_MBR_S1AP_UEContextModificationFailure_1[] = {
	{ ATF_POINTER, 0, offsetof(struct S1AP_UEContextModificationFailure, protocolIEs),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_S1AP_ProtocolIE_Container_8143P31,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"protocolIEs"
		},
};
static const ber_tlv_tag_t asn_DEF_S1AP_UEContextModificationFailure_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_S1AP_UEContextModificationFailure_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* protocolIEs */
};
asn_SEQUENCE_specifics_t asn_SPC_S1AP_UEContextModificationFailure_specs_1 = {
	sizeof(struct S1AP_UEContextModificationFailure),
	offsetof(struct S1AP_UEContextModificationFailure, _asn_ctx),
	asn_MAP_S1AP_UEContextModificationFailure_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_S1AP_UEContextModificationFailure = {
	"UEContextModificationFailure",
	"UEContextModificationFailure",
	&asn_OP_SEQUENCE,
	asn_DEF_S1AP_UEContextModificationFailure_tags_1,
	sizeof(asn_DEF_S1AP_UEContextModificationFailure_tags_1)
		/sizeof(asn_DEF_S1AP_UEContextModificationFailure_tags_1[0]), /* 1 */
	asn_DEF_S1AP_UEContextModificationFailure_tags_1,	/* Same as above */
	sizeof(asn_DEF_S1AP_UEContextModificationFailure_tags_1)
		/sizeof(asn_DEF_S1AP_UEContextModificationFailure_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_S1AP_UEContextModificationFailure_1,
	1,	/* Elements count */
	&asn_SPC_S1AP_UEContextModificationFailure_specs_1	/* Additional specs */
};

