/*
 * Copyright (C) 2019-2026 by Sukchan Lee <acetcom@gmail.com>
 *
 * This file is part of Open5GS.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#if !defined(OGS_SBI_INSIDE) && !defined(OGS_SBI_COMPILATION)
#error "This header cannot be included directly."
#endif

#ifndef OGS_SBI_TYPES_H
#define OGS_SBI_TYPES_H

#ifdef __cplusplus
extern "C" {
#endif

#define OGS_SBI_INTERFACE_NAME_SEPP "sepp"
#define OGS_SBI_INTERFACE_NAME_N32F "n32f"

#define OGS_SBI_SERVICE_NAME_N32C_HANDSHAKE "n32c-handshake"

#define OGS_SBI_SERVICE_NAME_NAMF_CALLBACK "namf-callback"
#define OGS_SBI_SERVICE_NAME_NSMF_CALLBACK "nsmf-callback"
#define OGS_SBI_SERVICE_NAME_NAMF_OAM "namf-oam"

#define OGS_SBI_MAX_NUM_OF_SERVICE_NAME 128

/*
 * Internal service-name IDs not defined in OpenAPI_service_name_e
 * Internal service-name IDs start at 1000
 */
#define OGS_SBI_SERVICE_NAME_ID_N32C_HANDSHAKE 1000
#define OGS_SBI_SERVICE_NAME_ID_NAMF_CALLBACK 1001
#define OGS_SBI_SERVICE_NAME_ID_NSMF_CALLBACK 1002

int ogs_sbi_service_name_id_from_string(const char *service_name);

OpenAPI_nf_type_e ogs_sbi_service_name_to_nf_type(
        OpenAPI_service_name_e service_name);

typedef enum {
    OGS_SBI_APP_ERRNO_NULL = 0,

    /*
     * Nsmf_PDUService
     *
     * TS29.502
     * 6.1.7 Error Handling
     * 6.1.7.3 Application Errors
     */
    OGS_SBI_APP_ERRNO_N1_SM_ERRNO,
    OGS_SBI_APP_ERRNO_N2_SM_ERRNO,
    OGS_SBI_APP_ERRNO_SNSSAI_DENIED,
    OGS_SBI_APP_ERRNO_DNN_DENIED,
    OGS_SBI_APP_ERRNO_PDUTYPE_DENIED,
    OGS_SBI_APP_ERRNO_SSC_DENIED,
    OGS_SBI_APP_ERRNO_SUBSCRIPTION_DENIED,
    OGS_SBI_APP_ERRNO_DNN_NOT_SUPPORTED,
    OGS_SBI_APP_ERRNO_PDUTYPE_NOT_SUPPORTED,
    OGS_SBI_APP_ERRNO_SSC_NOT_SUPPORTED,
    OGS_SBI_APP_ERRNO_HOME_ROUTED_ROAMING_REQUIRED,
    OGS_SBI_APP_ERRNO_OUT_OF_LADN_SERVICE_AREA,
    OGS_SBI_APP_ERRNO_PRIORITIZED_SERVICES_ONLY,
    OGS_SBI_APP_ERRNO_PDU_SESSION_ANCHOR_CHANGE,
    OGS_SBI_APP_ERRNO_TARGET_MME_CAPABILITY,
    OGS_SBI_APP_ERRNO_NO_EPS_5GS_CONTINUITY,
    OGS_SBI_APP_ERRNO_UNABLE_TO_PAGE_UE,
    OGS_SBI_APP_ERRNO_UE_NOT_RESPONDING,
    OGS_SBI_APP_ERRNO_REJECTED_BY_UE,
    OGS_SBI_APP_ERRNO_REJECTED_DUE_VPLMN_POLICY,
    OGS_SBI_APP_ERRNO_HO_TAU_IN_PROGRESS,
    OGS_SBI_APP_ERRNO_INTEGRITY_PROTECTED_MDR_NOT_ACCEPTABLE,
    OGS_SBI_APP_ERRNO_EBI_EXHAUSTED,
    OGS_SBI_APP_ERRNO_EBI_REJECTED_LOCAL_POLICY,
    OGS_SBI_APP_ERRNO_EBI_REJECTED_NO_N26,
    OGS_SBI_APP_ERRNO_DEFAULT_EPS_BEARER_INACTIVE,
    OGS_SBI_APP_ERRNO_HANDOVER_RESOURCE_ALLOCATION_FAILURE,
    OGS_SBI_APP_ERRNO_LATE_OVERLAPPING_REQUEST,
    OGS_SBI_APP_ERRNO_DEFAULT_EBI_NOT_TRANSFERRED,
    OGS_SBI_APP_ERRNO_NOT_SUPPORTED_WITH_ISMF,
    OGS_SBI_APP_ERRNO_SERVICE_NOT_AUTHORIZED_BY_NEXT_HOP,
    OGS_SBI_APP_ERRNO_NO_DATA_FORWARDING,
    OGS_SBI_APP_ERRNO_S_NSSAI_UNAVAILABLE_DUE_TO_NSAC,
    OGS_SBI_APP_ERRNO_EXCEEDED_UE_SLICE_DATA_RATE,
    OGS_SBI_APP_ERRNO_EXCEEDED_SLICE_DATA_RATE,
    OGS_SBI_APP_ERRNO_CONTEXT_NOT_FOUND,
    OGS_SBI_APP_ERRNO_HIGHER_PRIORITY_REQUEST_ONGOING,
    OGS_SBI_APP_ERRNO_UE_IN_CM_IDLE_STATE,
    OGS_SBI_APP_ERRNO_INSUFFICIENT_RESOURCES_SLICE,
    OGS_SBI_APP_ERRNO_INSUFFICIENT_RESOURCES_SLICE_DNN,
    OGS_SBI_APP_ERRNO_DNN_CONGESTION,
    OGS_SBI_APP_ERRNO_S_NSSAI_CONGESTION,
    OGS_SBI_APP_ERRNO_PEER_NOT_RESPONDING,
    OGS_SBI_APP_ERRNO_NETWORK_FAILURE,
    OGS_SBI_APP_ERRNO_UPF_NOT_RESPONDING,
    OGS_SBI_APP_ERRNO_UE_NOT_REACHABLE,

    OGS_SBI_MAX_NUM_OF_APP_ERRNO,
} ogs_sbi_app_errno_e;

#define OGS_SBI_APP_STRERROR_N1_SM_ERROR "N1_SM_ERROR"
#define OGS_SBI_APP_STRERROR_N2_SM_ERROR "N2_SM_ERROR"
#define OGS_SBI_APP_STRERROR_SNSSAI_DENIED "SNSSAI_DENIED"
#define OGS_SBI_APP_STRERROR_DNN_DENIED "DNN_DENIED"
#define OGS_SBI_APP_STRERROR_PDUTYPE_DENIED "PDUTYPE_DENIED"
#define OGS_SBI_APP_STRERROR_SSC_DENIED "SSC_DENIED"
#define OGS_SBI_APP_STRERROR_SUBSCRIPTION_DENIED "SUBSCRIPTION_DENIED"
#define OGS_SBI_APP_STRERROR_DNN_NOT_SUPPORTED "DNN_NOT_SUPPORTED"
#define OGS_SBI_APP_STRERROR_PDUTYPE_NOT_SUPPORTED "PDUTYPE_NOT_SUPPORTED"
#define OGS_SBI_APP_STRERROR_SSC_NOT_SUPPORTED "SSC_NOT_SUPPORTED"
#define OGS_SBI_APP_STRERROR_HOME_ROUTED_ROAMING_REQUIRED "HOME_ROUTED_ROAMING_REQUIRED"
#define OGS_SBI_APP_STRERROR_OUT_OF_LADN_SERVICE_AREA "OUT_OF_LADN_SERVICE_AREA"
#define OGS_SBI_APP_STRERROR_PRIORITIZED_SERVICES_ONLY "PRIORITIZED_SERVICES_ONLY"
#define OGS_SBI_APP_STRERROR_PDU_SESSION_ANCHOR_CHANGE "PDU_SESSION_ANCHOR_CHANGE"
#define OGS_SBI_APP_STRERROR_TARGET_MME_CAPABILITY "TARGET_MME_CAPABILITY"
#define OGS_SBI_APP_STRERROR_NO_EPS_5GS_CONTINUITY "NO_EPS_5GS_CONTINUITY"
#define OGS_SBI_APP_STRERROR_UNABLE_TO_PAGE_UE "UNABLE_TO_PAGE_UE"
#define OGS_SBI_APP_STRERROR_UE_NOT_RESPONDING "UE_NOT_RESPONDING"
#define OGS_SBI_APP_STRERROR_REJECTED_BY_UE "REJECTED_BY_UE"
#define OGS_SBI_APP_STRERROR_REJECTED_DUE_VPLMN_POLICY "REJECTED_DUE_VPLMN_POLICY"
#define OGS_SBI_APP_STRERROR_HO_TAU_IN_PROGRESS "HO_TAU_IN_PROGRESS"
#define OGS_SBI_APP_STRERROR_INTEGRITY_PROTECTED_MDR_NOT_ACCEPTABLE "INTEGRITY_PROTECTED_MDR_NOT_ACCEPTABLE"
#define OGS_SBI_APP_STRERROR_EBI_EXHAUSTED "EBI_EXHAUSTED"
#define OGS_SBI_APP_STRERROR_EBI_REJECTED_LOCAL_POLICY "EBI_REJECTED_LOCAL_POLICY"
#define OGS_SBI_APP_STRERROR_EBI_REJECTED_NO_N26 "EBI_REJECTED_NO_N26"
#define OGS_SBI_APP_STRERROR_DEFAULT_EPS_BEARER_INACTIVE "DEFAULT_EPS_BEARER_INACTIVE"
#define OGS_SBI_APP_STRERROR_HANDOVER_RESOURCE_ALLOCATION_FAILURE "HANDOVER_RESOURCE_ALLOCATION_FAILURE"
#define OGS_SBI_APP_STRERROR_LATE_OVERLAPPING_REQUEST "LATE_OVERLAPPING_REQUEST"
#define OGS_SBI_APP_STRERROR_DEFAULT_EBI_NOT_TRANSFERRED "DEFAULT_EBI_NOT_TRANSFERRED"
#define OGS_SBI_APP_STRERROR_NOT_SUPPORTED_WITH_ISMF "NOT_SUPPORTED_WITH_ISMF"
#define OGS_SBI_APP_STRERROR_SERVICE_NOT_AUTHORIZED_BY_NEXT_HOP "SERVICE_NOT_AUTHORIZED_BY_NEXT_HOP"
#define OGS_SBI_APP_STRERROR_NO_DATA_FORWARDING "NO_DATA_FORWARDING"
#define OGS_SBI_APP_STRERROR_S_NSSAI_UNAVAILABLE_DUE_TO_NSAC "S_NSSAI_UNAVAILABLE_DUE_TO_NSAC"
#define OGS_SBI_APP_STRERROR_EXCEEDED_UE_SLICE_DATA_RATE "EXCEEDED_UE_SLICE_DATA_RATE"
#define OGS_SBI_APP_STRERROR_EXCEEDED_SLICE_DATA_RATE "EXCEEDED_SLICE_DATA_RATE"
#define OGS_SBI_APP_STRERROR_CONTEXT_NOT_FOUND "CONTEXT_NOT_FOUND"
#define OGS_SBI_APP_STRERROR_HIGHER_PRIORITY_REQUEST_ONGOING "HIGHER_PRIORITY_REQUEST_ONGOING"
#define OGS_SBI_APP_STRERROR_UE_IN_CM_IDLE_STATE "UE_IN_CM_IDLE_STATE"
#define OGS_SBI_APP_STRERROR_INSUFFICIENT_RESOURCES_SLICE "INSUFFICIENT_RESOURCES_SLICE"
#define OGS_SBI_APP_STRERROR_INSUFFICIENT_RESOURCES_SLICE_DNN "INSUFFICIENT_RESOURCES_SLICE_DNN"
#define OGS_SBI_APP_STRERROR_DNN_CONGESTION "DNN_CONGESTION"
#define OGS_SBI_APP_STRERROR_S_NSSAI_CONGESTION "S_NSSAI_CONGESTION"
#define OGS_SBI_APP_STRERROR_PEER_NOT_RESPONDING "PEER_NOT_RESPONDING"
#define OGS_SBI_APP_STRERROR_NETWORK_FAILURE "NETWORK_FAILURE"
#define OGS_SBI_APP_STRERROR_UPF_NOT_RESPONDING "UPF_NOT_RESPONDING"
#define OGS_SBI_APP_STRERROR_UE_NOT_REACHABLE "UE_NOT_REACHABLE"

const char *ogs_sbi_app_strerror(ogs_sbi_app_errno_e e);
ogs_sbi_app_errno_e ogs_sbi_app_errno(const char *str);

#ifdef __cplusplus
}
#endif

#endif /* OGS_SBI_TYPES_H */
