/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "../support/fix-a90.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_S1ap_CNDomain_H_
#define	_S1ap_CNDomain_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum S1ap_CNDomain {
	S1ap_CNDomain_ps	= 0,
	S1ap_CNDomain_cs	= 1
} e_S1ap_CNDomain;

/* S1ap-CNDomain */
typedef long	 S1ap_CNDomain_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_S1ap_CNDomain;
asn_struct_free_f S1ap_CNDomain_free;
asn_struct_print_f S1ap_CNDomain_print;
asn_constr_check_f S1ap_CNDomain_constraint;
ber_type_decoder_f S1ap_CNDomain_decode_ber;
der_type_encoder_f S1ap_CNDomain_encode_der;
xer_type_decoder_f S1ap_CNDomain_decode_xer;
xer_type_encoder_f S1ap_CNDomain_encode_xer;
per_type_decoder_f S1ap_CNDomain_decode_uper;
per_type_encoder_f S1ap_CNDomain_encode_uper;
per_type_decoder_f S1ap_CNDomain_decode_aper;
per_type_encoder_f S1ap_CNDomain_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _S1ap_CNDomain_H_ */
#include "asn_internal.h"
