#!/bin/bash

version=0.9.0

display_help() {
    echo "open5gs_conf: Open5Gs Database Configuration Tool ($version)"
    echo "COMMANDS:" >&2
    echo "   add {imsi key opc}: adds a user to the network "
    echo "   remove {imsi}: removes a user from the network"
    echo "   reset: WIPES OUT the database and restores it to an empty default"
    echo "   help: displays this message and exits"
}


if [ "$#" -lt 1 ]; then
	display_help
	exit 1
fi

if [ "$1" = "help" ]; then
	display_help
	exit 1
fi

if [ "$1" = "add" ]; then
	if [ "$#" -ne 4 ]; then
		echo "open5gs_conf: incorrect number of args, format is \"open5gs_conf add imsi key opc\""
		exit 1
	fi
	IMSI=$2 
	KI=$3
	OPC=$4

	mongo --eval "db.subscribers.insert({ \"imsi\" : \"$IMSI\", \"pdn\" : [ { \"apn\" : \"internet\", \"_id\" : ObjectId(\"5daf349363b34e2c75fee3ee\"), \"pcc_rule\" : [ ], \"pgw\" : { \"addr\" : \"127.0.0.3\" }, \"ambr\" : { \"downlink\" : NumberLong(1024000), \"uplink\" : NumberLong(1024000) }, \"qos\" : { \"qci\" : NumberInt(9), \"arp\" : { \"priority_level\" : NumberInt(8), \"pre_emption_vulnerability\" : NumberInt(1), \"pre_emption_capability\" : NumberInt(1) } }, \"type\" : NumberInt(2) } ], \"ambr\" : { \"downlink\" : NumberLong(1024000), \"uplink\" : NumberLong(1024000) }, \"subscribed_rau_tau_timer\" : NumberInt(12), \"network_access_mode\" : NumberInt(2), \"subscriber_status\" : NumberInt(0), \"access_restriction_data\" : NumberInt(32), \"security\" : { \"k\" : \"$KI\", \"amf\" : \"8000\", \"op\" : null, \"opc\" : \"$OPC\" }, \"__v\" : 0 });" open5gs
	exit 0
fi

if [ "$1" = "remove" ]; then
	if [ "$#" -ne 2 ]; then
		echo "open5gs_conf: incorrect number of args, format is \"open5gs_conf remove imsi\""
		exit 1
	fi

	IMSI=$2 
	mongo --eval "db.subscribers.remove({\"imsi\": \"$IMSI\"});" open5gs
	exit 0
fi

display_help
