/*
 * analytics_subset.h
 *
 * 
 */

#ifndef _OpenAPI_analytics_subset_H_
#define _OpenAPI_analytics_subset_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef enum { OpenAPI_analytics_subset_NULL = 0, OpenAPI_analytics_subset_NUM_OF_UE_REG, OpenAPI_analytics_subset_NUM_OF_PDU_SESS_ESTBL, OpenAPI_analytics_subset_RES_USAGE, OpenAPI_analytics_subset_NUM_OF_EXCEED_RES_USAGE_LOAD_LEVEL_THR, OpenAPI_analytics_subset_PERIOD_OF_EXCEED_RES_USAGE_LOAD_LEVEL_THR, OpenAPI_analytics_subset_EXCEED_LOAD_LEVEL_THR_IND, OpenAPI_analytics_subset_LIST_OF_TOP_APP_UL, OpenAPI_analytics_subset_LIST_OF_TOP_APP_DL, OpenAPI_analytics_subset_NF_STATUS, OpenAPI_analytics_subset_NF_RESOURCE_USAGE, OpenAPI_analytics_subset_NF_LOAD, OpenAPI_analytics_subset_NF_PEAK_LOAD, OpenAPI_analytics_subset_NF_LOAD_AVG_IN_AOI, OpenAPI_analytics_subset_DISPER_AMOUNT, OpenAPI_analytics_subset_DISPER_CLASS, OpenAPI_analytics_subset_RANKING, OpenAPI_analytics_subset_PERCENTILE_RANKING, OpenAPI_analytics_subset_RSSI, OpenAPI_analytics_subset_RTT, OpenAPI_analytics_subset_TRAFFIC_INFO, OpenAPI_analytics_subset_NUMBER_OF_UES, OpenAPI_analytics_subset_APP_LIST_FOR_UE_COMM, OpenAPI_analytics_subset_N4_SESS_INACT_TIMER_FOR_UE_COMM, OpenAPI_analytics_subset_AVG_TRAFFIC_RATE, OpenAPI_analytics_subset_MAX_TRAFFIC_RATE, OpenAPI_analytics_subset_AGG_TRAFFIC_RATE, OpenAPI_analytics_subset_VAR_TRAFFIC_RATE, OpenAPI_analytics_subset_AVG_PACKET_DELAY, OpenAPI_analytics_subset_MAX_PACKET_DELAY, OpenAPI_analytics_subset_VAR_PACKET_DELAY, OpenAPI_analytics_subset_AVG_PACKET_LOSS_RATE, OpenAPI_analytics_subset_MAX_PACKET_LOSS_RATE, OpenAPI_analytics_subset_VAR_PACKET_LOSS_RATE, OpenAPI_analytics_subset_UE_LOCATION, OpenAPI_analytics_subset_LIST_OF_HIGH_EXP_UE, OpenAPI_analytics_subset_LIST_OF_MEDIUM_EXP_UE, OpenAPI_analytics_subset_LIST_OF_LOW_EXP_UE, OpenAPI_analytics_subset_AVG_UL_PKT_DROP_RATE, OpenAPI_analytics_subset_VAR_UL_PKT_DROP_RATE, OpenAPI_analytics_subset_AVG_DL_PKT_DROP_RATE, OpenAPI_analytics_subset_VAR_DL_PKT_DROP_RATE, OpenAPI_analytics_subset_AVG_UL_PKT_DELAY, OpenAPI_analytics_subset_VAR_UL_PKT_DELAY, OpenAPI_analytics_subset_AVG_DL_PKT_DELAY, OpenAPI_analytics_subset_VAR_DL_PKT_DELAY, OpenAPI_analytics_subset_TRAFFIC_MATCH_TD, OpenAPI_analytics_subset_TRAFFIC_UNMATCH_TD, OpenAPI_analytics_subset_NUMBER_OF_UE, OpenAPI_analytics_subset_UE_GEOG_DIST, OpenAPI_analytics_subset_UE_DIRECTION, OpenAPI_analytics_subset_AVG_E2E_UL_PKT_DELAY, OpenAPI_analytics_subset_VAR_E2E_UL_PKT_DELAY, OpenAPI_analytics_subset_AVG_E2E_DL_PKT_DELAY, OpenAPI_analytics_subset_VAR_E2E_DL_PKT_DELAY, OpenAPI_analytics_subset_AVG_E2E_UL_PKT_LOSS_RATE, OpenAPI_analytics_subset_VAR_E2E_UL_PKT_LOSS_RATE, OpenAPI_analytics_subset_AVG_E2E_DL_PKT_LOSS_RATE, OpenAPI_analytics_subset_VAR_E2E_DL_PKT_LOSS_RATE, OpenAPI_analytics_subset_E2E_DATA_VOL_TRANS_TIME_FOR_UE_LIST, OpenAPI_analytics_subset_NUM_OF_UE, OpenAPI_analytics_subset_MOV_UE_RATIO, OpenAPI_analytics_subset_AVR_SPEED, OpenAPI_analytics_subset_SPEED_THRESHOLD, OpenAPI_analytics_subset_MOV_UE_DIRECTION, OpenAPI_analytics_subset_IN_OUT_PERCENT, OpenAPI_analytics_subset_TIME_TO_COLLISION } OpenAPI_analytics_subset_e;

char* OpenAPI_analytics_subset_ToString(OpenAPI_analytics_subset_e analytics_subset);

OpenAPI_analytics_subset_e OpenAPI_analytics_subset_FromString(char* analytics_subset);

#ifdef __cplusplus
}
#endif

#endif /* _OpenAPI_analytics_subset_H_ */

