/*
 * analytics_subset_any_of.h
 *
 * 
 */

#ifndef _OpenAPI_analytics_subset_any_of_H_
#define _OpenAPI_analytics_subset_any_of_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef enum { OpenAPI_analytics_subset_any_of_NULL = 0, OpenAPI_analytics_subset_any_of_NUM_OF_UE_REG, OpenAPI_analytics_subset_any_of_NUM_OF_PDU_SESS_ESTBL, OpenAPI_analytics_subset_any_of_RES_USAGE, OpenAPI_analytics_subset_any_of_NUM_OF_EXCEED_RES_USAGE_LOAD_LEVEL_THR, OpenAPI_analytics_subset_any_of_PERIOD_OF_EXCEED_RES_USAGE_LOAD_LEVEL_THR, OpenAPI_analytics_subset_any_of_EXCEED_LOAD_LEVEL_THR_IND, OpenAPI_analytics_subset_any_of_LIST_OF_TOP_APP_UL, OpenAPI_analytics_subset_any_of_LIST_OF_TOP_APP_DL, OpenAPI_analytics_subset_any_of_NF_STATUS, OpenAPI_analytics_subset_any_of_NF_RESOURCE_USAGE, OpenAPI_analytics_subset_any_of_NF_LOAD, OpenAPI_analytics_subset_any_of_NF_PEAK_LOAD, OpenAPI_analytics_subset_any_of_NF_LOAD_AVG_IN_AOI, OpenAPI_analytics_subset_any_of_DISPER_AMOUNT, OpenAPI_analytics_subset_any_of_DISPER_CLASS, OpenAPI_analytics_subset_any_of_RANKING, OpenAPI_analytics_subset_any_of_PERCENTILE_RANKING, OpenAPI_analytics_subset_any_of_RSSI, OpenAPI_analytics_subset_any_of_RTT, OpenAPI_analytics_subset_any_of_TRAFFIC_INFO, OpenAPI_analytics_subset_any_of_NUMBER_OF_UES, OpenAPI_analytics_subset_any_of_APP_LIST_FOR_UE_COMM, OpenAPI_analytics_subset_any_of_N4_SESS_INACT_TIMER_FOR_UE_COMM, OpenAPI_analytics_subset_any_of_AVG_TRAFFIC_RATE, OpenAPI_analytics_subset_any_of_MAX_TRAFFIC_RATE, OpenAPI_analytics_subset_any_of_AVG_PACKET_DELAY, OpenAPI_analytics_subset_any_of_MAX_PACKET_DELAY, OpenAPI_analytics_subset_any_of_AVG_PACKET_LOSS_RATE, OpenAPI_analytics_subset_any_of_UE_LOCATION, OpenAPI_analytics_subset_any_of_LIST_OF_HIGH_EXP_UE, OpenAPI_analytics_subset_any_of_LIST_OF_MEDIUM_EXP_UE, OpenAPI_analytics_subset_any_of_LIST_OF_LOW_EXP_UE, OpenAPI_analytics_subset_any_of_AVG_UL_PKT_DROP_RATE, OpenAPI_analytics_subset_any_of_VAR_UL_PKT_DROP_RATE, OpenAPI_analytics_subset_any_of_AVG_DL_PKT_DROP_RATE, OpenAPI_analytics_subset_any_of_VAR_DL_PKT_DROP_RATE, OpenAPI_analytics_subset_any_of_AVG_UL_PKT_DELAY, OpenAPI_analytics_subset_any_of_VAR_UL_PKT_DELAY, OpenAPI_analytics_subset_any_of_AVG_DL_PKT_DELAY, OpenAPI_analytics_subset_any_of_VAR_DL_PKT_DELAY } OpenAPI_analytics_subset_any_of_e;

char* OpenAPI_analytics_subset_any_of_ToString(OpenAPI_analytics_subset_any_of_e analytics_subset_any_of);

OpenAPI_analytics_subset_any_of_e OpenAPI_analytics_subset_any_of_FromString(char* analytics_subset_any_of);

#ifdef __cplusplus
}
#endif

#endif /* _OpenAPI_analytics_subset_any_of_H_ */

