
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include "cause.h"

char* OpenAPI_cause_ToString(OpenAPI_cause_e cause)
{
    const char *causeArray[] =  { "NULL", "REL_DUE_TO_HO", "EPS_FALLBACK", "REL_DUE_TO_UP_SEC", "DNN_CONGESTION", "S_NSSAI_CONGESTION", "REL_DUE_TO_REACTIVATION", "5G_AN_NOT_RESPONDING", "REL_DUE_TO_SLICE_NOT_AVAILABLE", "REL_DUE_TO_DUPLICATE_SESSION_ID", "PDU_SESSION_STATUS_MISMATCH", "HO_FAILURE", "INSUFFICIENT_UP_RESOURCES", "PDU_SESSION_HANDED_OVER", "PDU_SESSION_RESUMED", "CN_ASSISTED_RAN_PARAMETER_TUNING", "ISMF_CONTEXT_TRANSFER", "SMF_CONTEXT_TRANSFER", "REL_DUE_TO_PS_TO_CS_HO", "REL_DUE_TO_SUBSCRIPTION_CHANGE", "HO_CANCEL", "REL_DUE_TO_SLICE_NOT_AUTHORIZED", "PDU_SESSION_HAND_OVER_FAILURE", "DDN_FAILURE_STATUS", "REL_DUE_TO_CP_ONLY_NOT_APPLICABLE", "NOT_SUPPORTED_WITH_ISMF", "CHANGED_ANCHOR_SMF", "CHANGED_INTERMEDIATE_SMF", "TARGET_DNAI_NOTIFICATION", "REL_DUE_TO_VPLMN_QOS_FAILURE", "REL_DUE_TO_SMF_NOT_SUPPORT_PSETR", "REL_DUE_TO_SNPN_SNPN_MOBILITY", "REL_DUE_TO_NO_HR_AGREEMENT", "REL_DUE_TO_UNSPECIFIED_REASON", "REL_DUE_TO_MOB_ACCESS_RESTRICTIONS", "REL_DUE_TO_SLICE_INACTIVITY", "REL_DUE_TO_NSI_NOT_AVAILABLE", "REL_DUE_TO_SNSSAI_DENIED", "REL_DUE_TO_DNN_DENIED", "REL_DUE_TO_PDUTYPE_DENIED", "REL_DUE_TO_SSC_DENIED", "REL_DUE_TO_SUBSCRIPTION_DENIED", "REL_DUE_TO_DNN_NOT_SUPPORTED", "REL_DUE_TO_PDUTYPE_NOT_SUPPORTED", "REL_DUE_TO_SSC_NOT_SUPPORTED", "REL_DUE_TO_INSUFFICIENT_RESOURCES_SLICE", "REL_DUE_TO_INSUFFICIENT_RESOURCES_SLICE_DNN", "REL_DUE_TO_DNN_CONGESTION", "REL_DUE_TO_S_NSSAI_CONGESTION", "REL_DUE_TO_PEER_NOT_RESPONDING", "REL_DUE_TO_NETWORK_FAILURE", "REL_DUE_TO_UPF_NOT_RESPONDING", "REL_DUE_TO_NO_EPS_5GS_CONTINUITY", "REL_DUE_TO_NOT_SUPPORTED_WITH_ISMF", "REL_DUE_TO_EXCEEDED_UE_SLICE_DATA_RATE", "REL_DUE_TO_EXCEEDED_SLICE_DATA_RATE", "REL_DUE_TO_CONTEXT_NOT_FOUND", "REL_DUE_TO_MBSR_NOT_AUTHORIZED", "DEACT_DUE_TO_UE_OUT_OF_SLICE_SUPPORT_AREA", "REJECT_DUE_TO_N1_SM_ERROR", "REL_DUE_TO_DUPLICATE_SESSION_EPDG", "REL_DUE_TO_AF_REQUESTED_SLICE_REPLACEMENT" };
    size_t sizeofArray = sizeof(causeArray) / sizeof(causeArray[0]);
    if (cause < sizeofArray)
        return (char *)causeArray[cause];
    else
        return (char *)"Unknown";
}

OpenAPI_cause_e OpenAPI_cause_FromString(char* cause)
{
    int stringToReturn = 0;
    const char *causeArray[] =  { "NULL", "REL_DUE_TO_HO", "EPS_FALLBACK", "REL_DUE_TO_UP_SEC", "DNN_CONGESTION", "S_NSSAI_CONGESTION", "REL_DUE_TO_REACTIVATION", "5G_AN_NOT_RESPONDING", "REL_DUE_TO_SLICE_NOT_AVAILABLE", "REL_DUE_TO_DUPLICATE_SESSION_ID", "PDU_SESSION_STATUS_MISMATCH", "HO_FAILURE", "INSUFFICIENT_UP_RESOURCES", "PDU_SESSION_HANDED_OVER", "PDU_SESSION_RESUMED", "CN_ASSISTED_RAN_PARAMETER_TUNING", "ISMF_CONTEXT_TRANSFER", "SMF_CONTEXT_TRANSFER", "REL_DUE_TO_PS_TO_CS_HO", "REL_DUE_TO_SUBSCRIPTION_CHANGE", "HO_CANCEL", "REL_DUE_TO_SLICE_NOT_AUTHORIZED", "PDU_SESSION_HAND_OVER_FAILURE", "DDN_FAILURE_STATUS", "REL_DUE_TO_CP_ONLY_NOT_APPLICABLE", "NOT_SUPPORTED_WITH_ISMF", "CHANGED_ANCHOR_SMF", "CHANGED_INTERMEDIATE_SMF", "TARGET_DNAI_NOTIFICATION", "REL_DUE_TO_VPLMN_QOS_FAILURE", "REL_DUE_TO_SMF_NOT_SUPPORT_PSETR", "REL_DUE_TO_SNPN_SNPN_MOBILITY", "REL_DUE_TO_NO_HR_AGREEMENT", "REL_DUE_TO_UNSPECIFIED_REASON", "REL_DUE_TO_MOB_ACCESS_RESTRICTIONS", "REL_DUE_TO_SLICE_INACTIVITY", "REL_DUE_TO_NSI_NOT_AVAILABLE", "REL_DUE_TO_SNSSAI_DENIED", "REL_DUE_TO_DNN_DENIED", "REL_DUE_TO_PDUTYPE_DENIED", "REL_DUE_TO_SSC_DENIED", "REL_DUE_TO_SUBSCRIPTION_DENIED", "REL_DUE_TO_DNN_NOT_SUPPORTED", "REL_DUE_TO_PDUTYPE_NOT_SUPPORTED", "REL_DUE_TO_SSC_NOT_SUPPORTED", "REL_DUE_TO_INSUFFICIENT_RESOURCES_SLICE", "REL_DUE_TO_INSUFFICIENT_RESOURCES_SLICE_DNN", "REL_DUE_TO_DNN_CONGESTION", "REL_DUE_TO_S_NSSAI_CONGESTION", "REL_DUE_TO_PEER_NOT_RESPONDING", "REL_DUE_TO_NETWORK_FAILURE", "REL_DUE_TO_UPF_NOT_RESPONDING", "REL_DUE_TO_NO_EPS_5GS_CONTINUITY", "REL_DUE_TO_NOT_SUPPORTED_WITH_ISMF", "REL_DUE_TO_EXCEEDED_UE_SLICE_DATA_RATE", "REL_DUE_TO_EXCEEDED_SLICE_DATA_RATE", "REL_DUE_TO_CONTEXT_NOT_FOUND", "REL_DUE_TO_MBSR_NOT_AUTHORIZED", "DEACT_DUE_TO_UE_OUT_OF_SLICE_SUPPORT_AREA", "REJECT_DUE_TO_N1_SM_ERROR", "REL_DUE_TO_DUPLICATE_SESSION_EPDG", "REL_DUE_TO_AF_REQUESTED_SLICE_REPLACEMENT" };
    size_t sizeofArray = sizeof(causeArray) / sizeof(causeArray[0]);
    while (stringToReturn < sizeofArray) {
        if (strcmp(cause, causeArray[stringToReturn]) == 0) {
            return stringToReturn;
        }
        stringToReturn++;
    }
    return 0;
}

