/*
 * trigger_type_any_of.h
 *
 * 
 */

#ifndef _OpenAPI_trigger_type_any_of_H_
#define _OpenAPI_trigger_type_any_of_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef enum { OpenAPI_trigger_type_any_of_NULL = 0, OpenAPI_trigger_type_any_of_QUOTA_THRESHOLD, OpenAPI_trigger_type_any_of_QHT, OpenAPI_trigger_type_any_of__FINAL, OpenAPI_trigger_type_any_of_QUOTA_EXHAUSTED, OpenAPI_trigger_type_any_of_VALIDITY_TIME, OpenAPI_trigger_type_any_of_OTHER_QUOTA_TYPE, OpenAPI_trigger_type_any_of_FORCED_REAUTHORISATION, OpenAPI_trigger_type_any_of_UNUSED_QUOTA_TIMER, OpenAPI_trigger_type_any_of_UNIT_COUNT_INACTIVITY_TIMER, OpenAPI_trigger_type_any_of_ABNORMAL_RELEASE, OpenAPI_trigger_type_any_of_QOS_CHANGE, OpenAPI_trigger_type_any_of_VOLUME_LIMIT, OpenAPI_trigger_type_any_of_TIME_LIMIT, OpenAPI_trigger_type_any_of_EVENT_LIMIT, OpenAPI_trigger_type_any_of_PLMN_CHANGE, OpenAPI_trigger_type_any_of_USER_LOCATION_CHANGE, OpenAPI_trigger_type_any_of_RAT_CHANGE, OpenAPI_trigger_type_any_of_SESSION_AMBR_CHANGE, OpenAPI_trigger_type_any_of_UE_TIMEZONE_CHANGE, OpenAPI_trigger_type_any_of_TARIFF_TIME_CHANGE, OpenAPI_trigger_type_any_of_MAX_NUMBER_OF_CHANGES_IN_CHARGING_CONDITIONS, OpenAPI_trigger_type_any_of_MANAGEMENT_INTERVENTION, OpenAPI_trigger_type_any_of_CHANGE_OF_UE_PRESENCE_IN_PRESENCE_REPORTING_AREA, OpenAPI_trigger_type_any_of_CHANGE_OF_3GPP_PS_DATA_OFF_STATUS, OpenAPI_trigger_type_any_of_SERVING_NODE_CHANGE, OpenAPI_trigger_type_any_of_REMOVAL_OF_UPF, OpenAPI_trigger_type_any_of_ADDITION_OF_UPF, OpenAPI_trigger_type_any_of_INSERTION_OF_ISMF, OpenAPI_trigger_type_any_of_REMOVAL_OF_ISMF, OpenAPI_trigger_type_any_of_CHANGE_OF_ISMF, OpenAPI_trigger_type_any_of_START_OF_SERVICE_DATA_FLOW, OpenAPI_trigger_type_any_of_ECGI_CHANGE, OpenAPI_trigger_type_any_of_TAI_CHANGE, OpenAPI_trigger_type_any_of_HANDOVER_CANCEL, OpenAPI_trigger_type_any_of_HANDOVER_START, OpenAPI_trigger_type_any_of_HANDOVER_COMPLETE, OpenAPI_trigger_type_any_of_GFBR_GUARANTEED_STATUS_CHANGE, OpenAPI_trigger_type_any_of_ADDITION_OF_ACCESS, OpenAPI_trigger_type_any_of_REMOVAL_OF_ACCESS, OpenAPI_trigger_type_any_of_START_OF_SDF_ADDITIONAL_ACCESS } OpenAPI_trigger_type_any_of_e;

char* OpenAPI_trigger_type_any_of_ToString(OpenAPI_trigger_type_any_of_e trigger_type_any_of);

OpenAPI_trigger_type_any_of_e OpenAPI_trigger_type_any_of_FromString(char* trigger_type_any_of);

#ifdef __cplusplus
}
#endif

#endif /* _OpenAPI_trigger_type_any_of_H_ */

