/*
 * trigger_type.h
 *
 * 
 */

#ifndef _OpenAPI_trigger_type_H_
#define _OpenAPI_trigger_type_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef enum { OpenAPI_trigger_type_NULL = 0, OpenAPI_trigger_type_QUOTA_THRESHOLD, OpenAPI_trigger_type_QHT, OpenAPI_trigger_type__FINAL, OpenAPI_trigger_type_QUOTA_EXHAUSTED, OpenAPI_trigger_type_VALIDITY_TIME, OpenAPI_trigger_type_OTHER_QUOTA_TYPE, OpenAPI_trigger_type_FORCED_REAUTHORISATION, OpenAPI_trigger_type_UNUSED_QUOTA_TIMER, OpenAPI_trigger_type_UNIT_COUNT_INACTIVITY_TIMER, OpenAPI_trigger_type_ABNORMAL_RELEASE, OpenAPI_trigger_type_QOS_CHANGE, OpenAPI_trigger_type_VOLUME_LIMIT, OpenAPI_trigger_type_TIME_LIMIT, OpenAPI_trigger_type_EVENT_LIMIT, OpenAPI_trigger_type_PLMN_CHANGE, OpenAPI_trigger_type_USER_LOCATION_CHANGE, OpenAPI_trigger_type_RAT_CHANGE, OpenAPI_trigger_type_SESSION_AMBR_CHANGE, OpenAPI_trigger_type_UE_TIMEZONE_CHANGE, OpenAPI_trigger_type_TARIFF_TIME_CHANGE, OpenAPI_trigger_type_MAX_NUMBER_OF_CHANGES_IN_CHARGING_CONDITIONS, OpenAPI_trigger_type_MANAGEMENT_INTERVENTION, OpenAPI_trigger_type_CHANGE_OF_UE_PRESENCE_IN_PRESENCE_REPORTING_AREA, OpenAPI_trigger_type_CHANGE_OF_3GPP_PS_DATA_OFF_STATUS, OpenAPI_trigger_type_SERVING_NODE_CHANGE, OpenAPI_trigger_type_REMOVAL_OF_UPF, OpenAPI_trigger_type_ADDITION_OF_UPF, OpenAPI_trigger_type_INSERTION_OF_ISMF, OpenAPI_trigger_type_REMOVAL_OF_ISMF, OpenAPI_trigger_type_CHANGE_OF_ISMF, OpenAPI_trigger_type_START_OF_SERVICE_DATA_FLOW, OpenAPI_trigger_type_ECGI_CHANGE, OpenAPI_trigger_type_TAI_CHANGE, OpenAPI_trigger_type_HANDOVER_CANCEL, OpenAPI_trigger_type_HANDOVER_START, OpenAPI_trigger_type_HANDOVER_COMPLETE, OpenAPI_trigger_type_GFBR_GUARANTEED_STATUS_CHANGE, OpenAPI_trigger_type_ADDITION_OF_ACCESS, OpenAPI_trigger_type_REMOVAL_OF_ACCESS, OpenAPI_trigger_type_START_OF_SDF_ADDITIONAL_ACCESS, OpenAPI_trigger_type_REDUNDANT_TRANSMISSION_CHANGE, OpenAPI_trigger_type_CGI_SAI_CHANGE, OpenAPI_trigger_type_RAI_CHANGE, OpenAPI_trigger_type_JOIN_MULTICAST, OpenAPI_trigger_type_MBS_DELIVERY_METHOD_CHANGE, OpenAPI_trigger_type_LEAVE_MULTICAST, OpenAPI_trigger_type_VSMF_CHANGE, OpenAPI_trigger_type_SNSSAI_REPLACEMENT, OpenAPI_trigger_type_SATELLITE_BACKHAUL_CATEGORY_CHANGE, OpenAPI_trigger_type_GEO_SATELLITE_ID_CHANGE, OpenAPI_trigger_type_SIP_INVITE, OpenAPI_trigger_type_SIP_RE_INVITE_OR_UPDATE, OpenAPI_trigger_type_SIP_2XX_ACKNOWLEDGING, OpenAPI_trigger_type_SIP_1XX_PROVISIONAL_RESPONSE, OpenAPI_trigger_type_SIP_4XX_5XX_OR_6XX_RESPONSE, OpenAPI_trigger_type_ANY_OTHER_SIP_MESSAGE, OpenAPI_trigger_type_SIP_BYE_MESSAGE, OpenAPI_trigger_type_SIP_2XX_ACKNOWLEDGING_A_SIP_BYE, OpenAPI_trigger_type_ABORTING_A_SIP_SESSION_SET_UP, OpenAPI_trigger_type_SIP_3XX_FINAL_OR_REDIRECTION_RESPONSE, OpenAPI_trigger_type_SIP_4XX_5XX_OR_6XX_FINAL_RESPONSE, OpenAPI_trigger_type_MBS_CONNECTION_ESTABLISHED_WITH_NG_RAN, OpenAPI_trigger_type_MBS_CONNECTION_RELEASED_WITH_NG_RAN, OpenAPI_trigger_type_MBS_CONNECTION_ESTABLISHED_WITH_UPF, OpenAPI_trigger_type_MBS_CONNECTION_RELEASED_WITH_UPF, OpenAPI_trigger_type_MBS_SESSION_ACTIVITY_STATUS_CHANGE_TO_ACTIVE, OpenAPI_trigger_type_MBS_SESSION_ACTIVITY_STATUS_CHANGE_TO_INACTIVE, OpenAPI_trigger_type_MBS_SESSION_CONTEXT_UPDATE, OpenAPI_trigger_type_NSAC_THRESHOLD_INITIAL, OpenAPI_trigger_type_NSAC_THRESHOLD_UPWARDS_REACHED, OpenAPI_trigger_type_NSAC_THRESHOLD_UPWARDS_CROSSED, OpenAPI_trigger_type_NSAC_THRESHOLD_DOWNWARDS_CROSSED, OpenAPI_trigger_type_NSAC_QUOTA_THRESHOLD, OpenAPI_trigger_type_NSAC_QUOTA_EXHAUSTED, OpenAPI_trigger_type_NSAC_VALIDITY_TIME, OpenAPI_trigger_type_NSAC_QHT, OpenAPI_trigger_type_NSAC_THRESHOLD_TERMINATION, OpenAPI_trigger_type_NS_TERMINATION } OpenAPI_trigger_type_e;

char* OpenAPI_trigger_type_ToString(OpenAPI_trigger_type_e trigger_type);

OpenAPI_trigger_type_e OpenAPI_trigger_type_FromString(char* trigger_type);

#ifdef __cplusplus
}
#endif

#endif /* _OpenAPI_trigger_type_H_ */

