/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../support/ngap-r16.1.0/38413-g10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#include "NGAP_PathSwitchRequestTransfer.h"

#include "NGAP_UserPlaneSecurityInformation.h"
#include "NGAP_ProtocolExtensionContainer.h"
static asn_TYPE_member_t asn_MBR_NGAP_PathSwitchRequestTransfer_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct NGAP_PathSwitchRequestTransfer, dL_NGU_UP_TNLInformation),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_NGAP_UPTransportLayerInformation,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dL-NGU-UP-TNLInformation"
		},
	{ ATF_POINTER, 2, offsetof(struct NGAP_PathSwitchRequestTransfer, dL_NGU_TNLInformationReused),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NGAP_DL_NGU_TNLInformationReused,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dL-NGU-TNLInformationReused"
		},
	{ ATF_POINTER, 1, offsetof(struct NGAP_PathSwitchRequestTransfer, userPlaneSecurityInformation),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NGAP_UserPlaneSecurityInformation,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"userPlaneSecurityInformation"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct NGAP_PathSwitchRequestTransfer, qosFlowAcceptedList),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NGAP_QosFlowAcceptedList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"qosFlowAcceptedList"
		},
	{ ATF_POINTER, 1, offsetof(struct NGAP_PathSwitchRequestTransfer, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NGAP_ProtocolExtensionContainer_7027P85,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_NGAP_PathSwitchRequestTransfer_oms_1[] = { 1, 2, 4 };
static const ber_tlv_tag_t asn_DEF_NGAP_PathSwitchRequestTransfer_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_NGAP_PathSwitchRequestTransfer_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* dL-NGU-UP-TNLInformation */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* dL-NGU-TNLInformationReused */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* userPlaneSecurityInformation */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* qosFlowAcceptedList */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* iE-Extensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_NGAP_PathSwitchRequestTransfer_specs_1 = {
	sizeof(struct NGAP_PathSwitchRequestTransfer),
	offsetof(struct NGAP_PathSwitchRequestTransfer, _asn_ctx),
	asn_MAP_NGAP_PathSwitchRequestTransfer_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_NGAP_PathSwitchRequestTransfer_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	5,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_NGAP_PathSwitchRequestTransfer = {
	"PathSwitchRequestTransfer",
	"PathSwitchRequestTransfer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_PathSwitchRequestTransfer_tags_1,
	sizeof(asn_DEF_NGAP_PathSwitchRequestTransfer_tags_1)
		/sizeof(asn_DEF_NGAP_PathSwitchRequestTransfer_tags_1[0]), /* 1 */
	asn_DEF_NGAP_PathSwitchRequestTransfer_tags_1,	/* Same as above */
	sizeof(asn_DEF_NGAP_PathSwitchRequestTransfer_tags_1)
		/sizeof(asn_DEF_NGAP_PathSwitchRequestTransfer_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_PathSwitchRequestTransfer_1,
	5,	/* Elements count */
	&asn_SPC_NGAP_PathSwitchRequestTransfer_specs_1	/* Additional specs */
};

