/*
 * Generated by asn1c-v1.4-43-gb7926896-2026-05-03 (https://github.com/mouse07410/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../support/ngap-r19.2.0/38413-j20.asn"
 * 	`asn1c -pdu=all -fprefix=NGAP_ -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-CBOR -no-gen-OER -no-gen-UPER`
 */

#ifndef	_NGAP_Area_ID_H_
#define	_NGAP_Area_ID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NGAP_Area_ID_PR {
	NGAP_Area_ID_PR_NOTHING,	/* No components present */
	NGAP_Area_ID_PR_tAI,
	NGAP_Area_ID_PR_globalRANNodeID,
	NGAP_Area_ID_PR_nR_CGI,
	NGAP_Area_ID_PR_choice_Extensions
} NGAP_Area_ID_PR;

/* Forward declarations */
struct NGAP_TAI;
struct NGAP_GlobalRANNodeID;
struct NGAP_NR_CGI;
struct NGAP_ProtocolIE_SingleContainer_14665P35;
struct NGAP_ProtocolIE_SingleContainer;

/* NGAP_Area-ID */
typedef struct NGAP_Area_ID {
	NGAP_Area_ID_PR present;
	union NGAP_Area_ID_u {
		struct NGAP_TAI	*tAI;
		struct NGAP_GlobalRANNodeID	*globalRANNodeID;
		struct NGAP_NR_CGI	*nR_CGI;
		struct NGAP_ProtocolIE_SingleContainer	*choice_Extensions;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_Area_ID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NGAP_Area_ID;
extern asn_CHOICE_specifics_t asn_SPC_NGAP_Area_ID_specs_1;
extern asn_TYPE_member_t asn_MBR_NGAP_Area_ID_1[4];
extern asn_per_constraints_t asn_PER_type_NGAP_Area_ID_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NGAP_Area_ID_H_ */
#include <asn_internal.h>
