/*
 * Generated by asn1c-v1.4-43-gb7926896-2026-05-03 (https://github.com/mouse07410/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../support/ngap-r19.2.0/38413-j20.asn"
 * 	`asn1c -pdu=all -fprefix=NGAP_ -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-CBOR -no-gen-OER -no-gen-UPER`
 */

#ifndef	_NGAP_IntersystemSONConfigurationTransfer_H_
#define	_NGAP_IntersystemSONConfigurationTransfer_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NGAP_IntersystemSONTransferType;
struct NGAP_IntersystemSONInformation;
struct NGAP_ProtocolExtensionContainer_14713P155;
struct NGAP_ProtocolExtensionContainer;

/* NGAP_IntersystemSONConfigurationTransfer */
typedef struct NGAP_IntersystemSONConfigurationTransfer {
	struct NGAP_IntersystemSONTransferType	*transferType;
	struct NGAP_IntersystemSONInformation	*intersystemSONInformation;
	struct NGAP_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_IntersystemSONConfigurationTransfer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NGAP_IntersystemSONConfigurationTransfer;
extern asn_SEQUENCE_specifics_t asn_SPC_NGAP_IntersystemSONConfigurationTransfer_specs_1;
extern asn_TYPE_member_t asn_MBR_NGAP_IntersystemSONConfigurationTransfer_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _NGAP_IntersystemSONConfigurationTransfer_H_ */
#include <asn_internal.h>
