/*
 * Generated by asn1c-v1.4-43-gb7926896-2026-05-03 (https://github.com/mouse07410/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../support/ngap-r19.2.0/38413-j20.asn"
 * 	`asn1c -pdu=all -fprefix=NGAP_ -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-CBOR -no-gen-OER -no-gen-UPER`
 */

#ifndef	_NGAP_ScheduledCommunicationTime_H_
#define	_NGAP_ScheduledCommunicationTime_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NGAP_ProtocolExtensionContainer_14713P372;
struct NGAP_ProtocolExtensionContainer;

/* NGAP_ScheduledCommunicationTime */
typedef struct NGAP_ScheduledCommunicationTime {
	BIT_STRING_t	*dayofWeek;	/* OPTIONAL */
	long	*timeofDayStart;	/* OPTIONAL */
	long	*timeofDayEnd;	/* OPTIONAL */
	struct NGAP_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ScheduledCommunicationTime_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ScheduledCommunicationTime;
extern asn_SEQUENCE_specifics_t asn_SPC_NGAP_ScheduledCommunicationTime_specs_1;
extern asn_TYPE_member_t asn_MBR_NGAP_ScheduledCommunicationTime_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _NGAP_ScheduledCommunicationTime_H_ */
#include <asn_internal.h>
