/*
 * Generated by asn1c-v1.4-43-gb7926896-2026-05-03 (https://github.com/mouse07410/asn1c)
 * From ASN.1 module "NGAP-PDU-Contents"
 * 	found in "../support/ngap-r19.2.0/38413-j20.asn"
 * 	`asn1c -pdu=all -fprefix=NGAP_ -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-CBOR -no-gen-OER -no-gen-UPER`
 */

#include "NGAP_UEContextSuspendFailure.h"

#include "NGAP_ProtocolIE-Container.h"
asn_TYPE_member_t asn_MBR_NGAP_UEContextSuspendFailure_1[] = {
	{ ATF_POINTER, 0, offsetof(struct NGAP_UEContextSuspendFailure, protocolIEs),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NGAP_ProtocolIE_Container_14662P20,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"protocolIEs"
		},
};
static const ber_tlv_tag_t asn_DEF_NGAP_UEContextSuspendFailure_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_NGAP_UEContextSuspendFailure_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* protocolIEs */
};
asn_SEQUENCE_specifics_t asn_SPC_NGAP_UEContextSuspendFailure_specs_1 = {
	sizeof(struct NGAP_UEContextSuspendFailure),
	offsetof(struct NGAP_UEContextSuspendFailure, _asn_ctx),
	asn_MAP_NGAP_UEContextSuspendFailure_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_NGAP_UEContextSuspendFailure = {
	"UEContextSuspendFailure",
	"UEContextSuspendFailure",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_UEContextSuspendFailure_tags_1,
	sizeof(asn_DEF_NGAP_UEContextSuspendFailure_tags_1)
		/sizeof(asn_DEF_NGAP_UEContextSuspendFailure_tags_1[0]), /* 1 */
	asn_DEF_NGAP_UEContextSuspendFailure_tags_1,	/* Same as above */
	sizeof(asn_DEF_NGAP_UEContextSuspendFailure_tags_1)
		/sizeof(asn_DEF_NGAP_UEContextSuspendFailure_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_NGAP_UEContextSuspendFailure_1,
	1,	/* Elements count */
	&asn_SPC_NGAP_UEContextSuspendFailure_specs_1	/* Additional specs */
};

