/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../support/ngap-r17.3.0/38413-h30.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NGAP_EUTRA_Paging_eDRX_Cycle_H_
#define	_NGAP_EUTRA_Paging_eDRX_Cycle_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NGAP_EUTRA_Paging_eDRX_Cycle {
	NGAP_EUTRA_Paging_eDRX_Cycle_hfhalf	= 0,
	NGAP_EUTRA_Paging_eDRX_Cycle_hf1	= 1,
	NGAP_EUTRA_Paging_eDRX_Cycle_hf2	= 2,
	NGAP_EUTRA_Paging_eDRX_Cycle_hf4	= 3,
	NGAP_EUTRA_Paging_eDRX_Cycle_hf6	= 4,
	NGAP_EUTRA_Paging_eDRX_Cycle_hf8	= 5,
	NGAP_EUTRA_Paging_eDRX_Cycle_hf10	= 6,
	NGAP_EUTRA_Paging_eDRX_Cycle_hf12	= 7,
	NGAP_EUTRA_Paging_eDRX_Cycle_hf14	= 8,
	NGAP_EUTRA_Paging_eDRX_Cycle_hf16	= 9,
	NGAP_EUTRA_Paging_eDRX_Cycle_hf32	= 10,
	NGAP_EUTRA_Paging_eDRX_Cycle_hf64	= 11,
	NGAP_EUTRA_Paging_eDRX_Cycle_hf128	= 12,
	NGAP_EUTRA_Paging_eDRX_Cycle_hf256	= 13
	/*
	 * Enumeration is extensible
	 */
} e_NGAP_EUTRA_Paging_eDRX_Cycle;

/* NGAP_EUTRA-Paging-eDRX-Cycle */
typedef long	 NGAP_EUTRA_Paging_eDRX_Cycle_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NGAP_EUTRA_Paging_eDRX_Cycle_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_EUTRA_Paging_eDRX_Cycle;
extern const asn_INTEGER_specifics_t asn_SPC_NGAP_EUTRA_Paging_eDRX_Cycle_specs_1;
asn_struct_free_f NGAP_EUTRA_Paging_eDRX_Cycle_free;
asn_struct_print_f NGAP_EUTRA_Paging_eDRX_Cycle_print;
asn_constr_check_f NGAP_EUTRA_Paging_eDRX_Cycle_constraint;
per_type_decoder_f NGAP_EUTRA_Paging_eDRX_Cycle_decode_aper;
per_type_encoder_f NGAP_EUTRA_Paging_eDRX_Cycle_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _NGAP_EUTRA_Paging_eDRX_Cycle_H_ */
#include <asn_internal.h>
