/*
 * Generated by asn1c-v1.4-43-gb7926896-2026-05-03 (https://github.com/mouse07410/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../support/ngap-r19.2.0/38413-j20.asn"
 * 	`asn1c -pdu=all -fprefix=NGAP_ -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-CBOR -no-gen-OER -no-gen-UPER`
 */

#include "NGAP_HLComActivate.h"

#include "NGAP_NR-Paging-Long-eDRX-Information-for-RRC-INACTIVE.h"
#include "NGAP_ProtocolExtensionContainer.h"
asn_TYPE_member_t asn_MBR_NGAP_HLComActivate_1[] = {
	{ ATF_POINTER, 0, offsetof(struct NGAP_HLComActivate, nR_Paging_Long_eDRX_Information_for_RRC_INACTIVE),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NGAP_NR_Paging_Long_eDRX_Information_for_RRC_INACTIVE,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"nR-Paging-Long-eDRX-Information-for-RRC-INACTIVE"
		},
	{ ATF_POINTER, 1, offsetof(struct NGAP_HLComActivate, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NGAP_ProtocolExtensionContainer_14713P148,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_NGAP_HLComActivate_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_NGAP_HLComActivate_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_NGAP_HLComActivate_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* nR-Paging-Long-eDRX-Information-for-RRC-INACTIVE */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_NGAP_HLComActivate_specs_1 = {
	sizeof(struct NGAP_HLComActivate),
	offsetof(struct NGAP_HLComActivate, _asn_ctx),
	asn_MAP_NGAP_HLComActivate_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_NGAP_HLComActivate_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_NGAP_HLComActivate = {
	"HLComActivate",
	"HLComActivate",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_HLComActivate_tags_1,
	sizeof(asn_DEF_NGAP_HLComActivate_tags_1)
		/sizeof(asn_DEF_NGAP_HLComActivate_tags_1[0]), /* 1 */
	asn_DEF_NGAP_HLComActivate_tags_1,	/* Same as above */
	sizeof(asn_DEF_NGAP_HLComActivate_tags_1)
		/sizeof(asn_DEF_NGAP_HLComActivate_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_NGAP_HLComActivate_1,
	2,	/* Elements count */
	&asn_SPC_NGAP_HLComActivate_specs_1	/* Additional specs */
};

