/*
 * Generated by asn1c-v1.4-43-gb7926896-2026-05-03 (https://github.com/mouse07410/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../support/ngap-r19.2.0/38413-j20.asn"
 * 	`asn1c -pdu=all -fprefix=NGAP_ -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-CBOR -no-gen-OER -no-gen-UPER`
 */

#include "NGAP_M6report-Interval.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_NGAP_M6report_Interval_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  4,  4,  0,  13 }	/* (0..13,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const asn_INTEGER_enum_map_t asn_MAP_NGAP_M6report_Interval_value2enum_1[] = {
	{ 0,	5,	"ms120" },
	{ 1,	5,	"ms240" },
	{ 2,	5,	"ms480" },
	{ 3,	5,	"ms640" },
	{ 4,	6,	"ms1024" },
	{ 5,	6,	"ms2048" },
	{ 6,	6,	"ms5120" },
	{ 7,	7,	"ms10240" },
	{ 8,	7,	"ms20480" },
	{ 9,	7,	"ms40960" },
	{ 10,	4,	"min1" },
	{ 11,	4,	"min6" },
	{ 12,	5,	"min12" },
	{ 13,	5,	"min30" }
	/* This list is extensible */
};
static int asn_validate_NGAP_M6report_Interval_1(const asn_TYPE_descriptor_t *td,
                       const void *sptr,
                       asn_app_constraint_failed_f *ctfailcb,
                       void* app_key) {
    if(! sptr) { return -1; }
    e_NGAP_M6report_Interval value = *(e_NGAP_M6report_Interval*)sptr;
    switch(value) {
    case NGAP_M6report_Interval_ms120:
    case NGAP_M6report_Interval_ms240:
    case NGAP_M6report_Interval_ms480:
    case NGAP_M6report_Interval_ms640:
    case NGAP_M6report_Interval_ms1024:
    case NGAP_M6report_Interval_ms2048:
    case NGAP_M6report_Interval_ms5120:
    case NGAP_M6report_Interval_ms10240:
    case NGAP_M6report_Interval_ms20480:
    case NGAP_M6report_Interval_ms40960:
    case NGAP_M6report_Interval_min1:
    case NGAP_M6report_Interval_min6:
    case NGAP_M6report_Interval_min12:
    case NGAP_M6report_Interval_min30:
        return 0;
    }
    return -1;
}
static const unsigned int asn_MAP_NGAP_M6report_Interval_enum2value_1[] = {
	10,	/* min1(10) */
	12,	/* min12(12) */
	13,	/* min30(13) */
	11,	/* min6(11) */
	4,	/* ms1024(4) */
	7,	/* ms10240(7) */
	0,	/* ms120(0) */
	5,	/* ms2048(5) */
	8,	/* ms20480(8) */
	1,	/* ms240(1) */
	9,	/* ms40960(9) */
	2,	/* ms480(2) */
	6,	/* ms5120(6) */
	3	/* ms640(3) */
	/* This list is extensible */
};
const asn_INTEGER_specifics_t asn_SPC_NGAP_M6report_Interval_specs_1 = {
	asn_MAP_NGAP_M6report_Interval_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_NGAP_M6report_Interval_enum2value_1,	/* N => "tag"; sorted by N */
	14,	/* Number of elements in the maps */
	15,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_NGAP_M6report_Interval_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_M6report_Interval = {
	"M6report-Interval",
	"M6report-Interval",
	&asn_OP_NativeEnumerated,
	asn_DEF_NGAP_M6report_Interval_tags_1,
	sizeof(asn_DEF_NGAP_M6report_Interval_tags_1)
		/sizeof(asn_DEF_NGAP_M6report_Interval_tags_1[0]), /* 1 */
	asn_DEF_NGAP_M6report_Interval_tags_1,	/* Same as above */
	sizeof(asn_DEF_NGAP_M6report_Interval_tags_1)
		/sizeof(asn_DEF_NGAP_M6report_Interval_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_NGAP_M6report_Interval_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		asn_validate_NGAP_M6report_Interval_1
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_NGAP_M6report_Interval_specs_1	/* Additional specs */
};

