/*
 * Generated by asn1c-v1.4-43-gb7926896-2026-05-03 (https://github.com/mouse07410/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../support/ngap-r19.2.0/38413-j20.asn"
 * 	`asn1c -pdu=all -fprefix=NGAP_ -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-CBOR -no-gen-OER -no-gen-UPER`
 */

#ifndef	_NGAP_UserPlaneFailureIndicationReport_H_
#define	_NGAP_UserPlaneFailureIndicationReport_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NGAP_UserPlaneFailureIndicationReport {
	NGAP_UserPlaneFailureIndicationReport_qos_flows_and_tunnel_to_be_released	= 0,
	NGAP_UserPlaneFailureIndicationReport_qoS_flows_to_be_moved	= 1,
	NGAP_UserPlaneFailureIndicationReport_new_transport_address_allocated	= 2
	/*
	 * Enumeration is extensible
	 */
} e_NGAP_UserPlaneFailureIndicationReport;

/* NGAP_UserPlaneFailureIndicationReport */
typedef long	 NGAP_UserPlaneFailureIndicationReport_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NGAP_UserPlaneFailureIndicationReport_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_UserPlaneFailureIndicationReport;
extern const asn_INTEGER_specifics_t asn_SPC_NGAP_UserPlaneFailureIndicationReport_specs_1;
asn_struct_free_f NGAP_UserPlaneFailureIndicationReport_free;
asn_struct_print_f NGAP_UserPlaneFailureIndicationReport_print;
asn_constr_check_f NGAP_UserPlaneFailureIndicationReport_constraint;
per_type_decoder_f NGAP_UserPlaneFailureIndicationReport_decode_aper;
per_type_encoder_f NGAP_UserPlaneFailureIndicationReport_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _NGAP_UserPlaneFailureIndicationReport_H_ */
#include <asn_internal.h>
