/*
 * Generated by asn1c-v1.4-43-gb7926896-2026-05-03 (https://github.com/mouse07410/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../support/ngap-r19.2.0/38413-j20.asn"
 * 	`asn1c -pdu=all -fprefix=NGAP_ -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-CBOR -no-gen-OER -no-gen-UPER`
 */

#ifndef	_NGAP_AIoT_Support_H_
#define	_NGAP_AIoT_Support_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NGAP_AIoT_Support {
	NGAP_AIoT_Support_aIoT_only	= 0,
	NGAP_AIoT_Support_aIoT_and_NRUu	= 1
	/*
	 * Enumeration is extensible
	 */
} e_NGAP_AIoT_Support;

/* NGAP_AIoT-Support */
typedef long	 NGAP_AIoT_Support_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NGAP_AIoT_Support_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_AIoT_Support;
extern const asn_INTEGER_specifics_t asn_SPC_NGAP_AIoT_Support_specs_1;
asn_struct_free_f NGAP_AIoT_Support_free;
asn_struct_print_f NGAP_AIoT_Support_print;
asn_constr_check_f NGAP_AIoT_Support_constraint;
per_type_decoder_f NGAP_AIoT_Support_decode_aper;
per_type_encoder_f NGAP_AIoT_Support_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _NGAP_AIoT_Support_H_ */
#include <asn_internal.h>
