/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18/NRPPA-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_DL_PRSMutingPattern_H_
#define	_DL_PRSMutingPattern_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DL_PRSMutingPattern_PR {
	DL_PRSMutingPattern_PR_NOTHING,	/* No components present */
	DL_PRSMutingPattern_PR_two,
	DL_PRSMutingPattern_PR_four,
	DL_PRSMutingPattern_PR_six,
	DL_PRSMutingPattern_PR_eight,
	DL_PRSMutingPattern_PR_sixteen,
	DL_PRSMutingPattern_PR_thirty_two,
	DL_PRSMutingPattern_PR_choice_extension
} DL_PRSMutingPattern_PR;

/* Forward declarations */
struct ProtocolIE_Single_Container;

/* DL-PRSMutingPattern */
typedef struct DL_PRSMutingPattern {
	DL_PRSMutingPattern_PR present;
	union DL_PRSMutingPattern_u {
		BIT_STRING_t	 two;
		BIT_STRING_t	 four;
		BIT_STRING_t	 six;
		BIT_STRING_t	 eight;
		BIT_STRING_t	 sixteen;
		BIT_STRING_t	 thirty_two;
		struct ProtocolIE_Single_Container	*choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DL_PRSMutingPattern_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DL_PRSMutingPattern;
extern asn_CHOICE_specifics_t asn_SPC_DL_PRSMutingPattern_specs_1;
extern asn_TYPE_member_t asn_MBR_DL_PRSMutingPattern_1[7];
extern asn_per_constraints_t asn_PER_type_DL_PRSMutingPattern_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _DL_PRSMutingPattern_H_ */
#include <asn_internal.h>
