/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18/NRPPA-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_DL_reference_signal_UERxTx_TD_H_
#define	_DL_reference_signal_UERxTx_TD_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DL_reference_signal_UERxTx_TD {
	DL_reference_signal_UERxTx_TD_csirs	= 0,
	DL_reference_signal_UERxTx_TD_prs	= 1
	/*
	 * Enumeration is extensible
	 */
} e_DL_reference_signal_UERxTx_TD;

/* DL-reference-signal-UERxTx-TD */
typedef long	 DL_reference_signal_UERxTx_TD_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_DL_reference_signal_UERxTx_TD_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_DL_reference_signal_UERxTx_TD;
extern const asn_INTEGER_specifics_t asn_SPC_DL_reference_signal_UERxTx_TD_specs_1;
asn_struct_free_f DL_reference_signal_UERxTx_TD_free;
asn_struct_print_f DL_reference_signal_UERxTx_TD_print;
asn_constr_check_f DL_reference_signal_UERxTx_TD_constraint;
per_type_decoder_f DL_reference_signal_UERxTx_TD_decode_aper;
per_type_encoder_f DL_reference_signal_UERxTx_TD_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _DL_reference_signal_UERxTx_TD_H_ */
#include <asn_internal.h>
