/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18/NRPPA-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#include "MeasurementPeriodicityNR-AoA.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_MeasurementPeriodicityNR_AoA_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  4,  4,  0,  13 }	/* (0..13,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const asn_INTEGER_enum_map_t asn_MAP_MeasurementPeriodicityNR_AoA_value2enum_1[] = {
	{ 0,	5,	"ms160" },
	{ 1,	5,	"ms320" },
	{ 2,	5,	"ms640" },
	{ 3,	6,	"ms1280" },
	{ 4,	6,	"ms2560" },
	{ 5,	6,	"ms5120" },
	{ 6,	7,	"ms10240" },
	{ 7,	7,	"ms20480" },
	{ 8,	7,	"ms40960" },
	{ 9,	7,	"ms61440" },
	{ 10,	7,	"ms81920" },
	{ 11,	8,	"ms368640" },
	{ 12,	8,	"ms737280" },
	{ 13,	9,	"ms1843200" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_MeasurementPeriodicityNR_AoA_enum2value_1[] = {
	6,	/* ms10240(6) */
	3,	/* ms1280(3) */
	0,	/* ms160(0) */
	13,	/* ms1843200(13) */
	7,	/* ms20480(7) */
	4,	/* ms2560(4) */
	1,	/* ms320(1) */
	11,	/* ms368640(11) */
	8,	/* ms40960(8) */
	5,	/* ms5120(5) */
	9,	/* ms61440(9) */
	2,	/* ms640(2) */
	12,	/* ms737280(12) */
	10	/* ms81920(10) */
	/* This list is extensible */
};
const asn_INTEGER_specifics_t asn_SPC_MeasurementPeriodicityNR_AoA_specs_1 = {
	asn_MAP_MeasurementPeriodicityNR_AoA_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_MeasurementPeriodicityNR_AoA_enum2value_1,	/* N => "tag"; sorted by N */
	14,	/* Number of elements in the maps */
	15,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_MeasurementPeriodicityNR_AoA_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_MeasurementPeriodicityNR_AoA = {
	"MeasurementPeriodicityNR-AoA",
	"MeasurementPeriodicityNR-AoA",
	&asn_OP_NativeEnumerated,
	asn_DEF_MeasurementPeriodicityNR_AoA_tags_1,
	sizeof(asn_DEF_MeasurementPeriodicityNR_AoA_tags_1)
		/sizeof(asn_DEF_MeasurementPeriodicityNR_AoA_tags_1[0]), /* 1 */
	asn_DEF_MeasurementPeriodicityNR_AoA_tags_1,	/* Same as above */
	sizeof(asn_DEF_MeasurementPeriodicityNR_AoA_tags_1)
		/sizeof(asn_DEF_MeasurementPeriodicityNR_AoA_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_MeasurementPeriodicityNR_AoA_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_MeasurementPeriodicityNR_AoA_specs_1	/* Additional specs */
};

