/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18/NRPPA-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_MeasurementPeriodicity_H_
#define	_MeasurementPeriodicity_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MeasurementPeriodicity {
	MeasurementPeriodicity_ms120	= 0,
	MeasurementPeriodicity_ms240	= 1,
	MeasurementPeriodicity_ms480	= 2,
	MeasurementPeriodicity_ms640	= 3,
	MeasurementPeriodicity_ms1024	= 4,
	MeasurementPeriodicity_ms2048	= 5,
	MeasurementPeriodicity_ms5120	= 6,
	MeasurementPeriodicity_ms10240	= 7,
	MeasurementPeriodicity_min1	= 8,
	MeasurementPeriodicity_min6	= 9,
	MeasurementPeriodicity_min12	= 10,
	MeasurementPeriodicity_min30	= 11,
	MeasurementPeriodicity_min60	= 12,
	/*
	 * Enumeration is extensible
	 */
	MeasurementPeriodicity_ms20480	= 13,
	MeasurementPeriodicity_ms40960	= 14,
	MeasurementPeriodicity_extended	= 15
} e_MeasurementPeriodicity;

/* MeasurementPeriodicity */
typedef long	 MeasurementPeriodicity_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_MeasurementPeriodicity_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_MeasurementPeriodicity;
extern const asn_INTEGER_specifics_t asn_SPC_MeasurementPeriodicity_specs_1;
asn_struct_free_f MeasurementPeriodicity_free;
asn_struct_print_f MeasurementPeriodicity_print;
asn_constr_check_f MeasurementPeriodicity_constraint;
per_type_decoder_f MeasurementPeriodicity_decode_aper;
per_type_encoder_f MeasurementPeriodicity_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _MeasurementPeriodicity_H_ */
#include <asn_internal.h>
