/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18/NRPPA-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_PosSRSInfo_H_
#define	_PosSRSInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SRSPosResourceID.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PosSRSInfo */
typedef struct PosSRSInfo {
	SRSPosResourceID_t	 posSRSResourceID;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PosSRSInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PosSRSInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_PosSRSInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_PosSRSInfo_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _PosSRSInfo_H_ */
#include <asn_internal.h>
