/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18/NRPPA-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#include "PRSTransmissionOffPerResource-Item.h"

#include "ProtocolExtensionContainer.h"
#include "PRSTransmissionOffIndicationPerResource-Item.h"
static int
memb_pRSTransmissionOffIndicationPerResourceList_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1UL && size <= 64UL)) {
		/* Perform validation of the inner elements */
		return SEQUENCE_OF_constraint(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_pRSTransmissionOffIndicationPerResourceList_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 6,  6,  1,  64 }	/* (SIZE(1..64)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_memb_pRSTransmissionOffIndicationPerResourceList_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 6,  6,  1,  64 }	/* (SIZE(1..64)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static asn_TYPE_member_t asn_MBR_pRSTransmissionOffIndicationPerResourceList_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_PRSTransmissionOffIndicationPerResource_Item,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_pRSTransmissionOffIndicationPerResourceList_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_pRSTransmissionOffIndicationPerResourceList_specs_3 = {
	sizeof(struct PRSTransmissionOffPerResource_Item__pRSTransmissionOffIndicationPerResourceList),
	offsetof(struct PRSTransmissionOffPerResource_Item__pRSTransmissionOffIndicationPerResourceList, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_pRSTransmissionOffIndicationPerResourceList_3 = {
	"pRSTransmissionOffIndicationPerResourceList",
	"pRSTransmissionOffIndicationPerResourceList",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_pRSTransmissionOffIndicationPerResourceList_tags_3,
	sizeof(asn_DEF_pRSTransmissionOffIndicationPerResourceList_tags_3)
		/sizeof(asn_DEF_pRSTransmissionOffIndicationPerResourceList_tags_3[0]) - 1, /* 1 */
	asn_DEF_pRSTransmissionOffIndicationPerResourceList_tags_3,	/* Same as above */
	sizeof(asn_DEF_pRSTransmissionOffIndicationPerResourceList_tags_3)
		/sizeof(asn_DEF_pRSTransmissionOffIndicationPerResourceList_tags_3[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_pRSTransmissionOffIndicationPerResourceList_constr_3,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_pRSTransmissionOffIndicationPerResourceList_3,
	1,	/* Single element */
	&asn_SPC_pRSTransmissionOffIndicationPerResourceList_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_PRSTransmissionOffPerResource_Item_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PRSTransmissionOffPerResource_Item, pRSResourceSetID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PRS_Resource_Set_ID,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"pRSResourceSetID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PRSTransmissionOffPerResource_Item, pRSTransmissionOffIndicationPerResourceList),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_pRSTransmissionOffIndicationPerResourceList_3,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			&asn_PER_memb_pRSTransmissionOffIndicationPerResourceList_constr_3,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			memb_pRSTransmissionOffIndicationPerResourceList_constraint_1
		},
		0, 0, /* No default value */
		"pRSTransmissionOffIndicationPerResourceList"
		},
	{ ATF_POINTER, 1, offsetof(struct PRSTransmissionOffPerResource_Item, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolExtensionContainer_128P69,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_PRSTransmissionOffPerResource_Item_oms_1[] = { 2 };
static const ber_tlv_tag_t asn_DEF_PRSTransmissionOffPerResource_Item_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_PRSTransmissionOffPerResource_Item_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* pRSResourceSetID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* pRSTransmissionOffIndicationPerResourceList */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_PRSTransmissionOffPerResource_Item_specs_1 = {
	sizeof(struct PRSTransmissionOffPerResource_Item),
	offsetof(struct PRSTransmissionOffPerResource_Item, _asn_ctx),
	asn_MAP_PRSTransmissionOffPerResource_Item_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_PRSTransmissionOffPerResource_Item_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_PRSTransmissionOffPerResource_Item = {
	"PRSTransmissionOffPerResource-Item",
	"PRSTransmissionOffPerResource-Item",
	&asn_OP_SEQUENCE,
	asn_DEF_PRSTransmissionOffPerResource_Item_tags_1,
	sizeof(asn_DEF_PRSTransmissionOffPerResource_Item_tags_1)
		/sizeof(asn_DEF_PRSTransmissionOffPerResource_Item_tags_1[0]), /* 1 */
	asn_DEF_PRSTransmissionOffPerResource_Item_tags_1,	/* Same as above */
	sizeof(asn_DEF_PRSTransmissionOffPerResource_Item_tags_1)
		/sizeof(asn_DEF_PRSTransmissionOffPerResource_Item_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_PRSTransmissionOffPerResource_Item_1,
	3,	/* Elements count */
	&asn_SPC_PRSTransmissionOffPerResource_Item_specs_1	/* Additional specs */
};

