/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18/NRPPA-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#include "RxTxTEG.h"

#include "TRP-Tx-TEGInformation.h"
#include "ProtocolExtensionContainer.h"
asn_TYPE_member_t asn_MBR_RxTxTEG_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RxTxTEG, tRP_RxTx_TEGInformation),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TRP_RxTx_TEGInformation,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"tRP-RxTx-TEGInformation"
		},
	{ ATF_POINTER, 2, offsetof(struct RxTxTEG, tRP_Tx_TEGInformation),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TRP_Tx_TEGInformation,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"tRP-Tx-TEGInformation"
		},
	{ ATF_POINTER, 1, offsetof(struct RxTxTEG, iE_extensions),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolExtensionContainer_128P134,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"iE-extensions"
		},
};
static const int asn_MAP_RxTxTEG_oms_1[] = { 1, 2 };
static const ber_tlv_tag_t asn_DEF_RxTxTEG_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RxTxTEG_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* tRP-RxTx-TEGInformation */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* tRP-Tx-TEGInformation */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* iE-extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_RxTxTEG_specs_1 = {
	sizeof(struct RxTxTEG),
	offsetof(struct RxTxTEG, _asn_ctx),
	asn_MAP_RxTxTEG_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_RxTxTEG_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RxTxTEG = {
	"RxTxTEG",
	"RxTxTEG",
	&asn_OP_SEQUENCE,
	asn_DEF_RxTxTEG_tags_1,
	sizeof(asn_DEF_RxTxTEG_tags_1)
		/sizeof(asn_DEF_RxTxTEG_tags_1[0]), /* 1 */
	asn_DEF_RxTxTEG_tags_1,	/* Same as above */
	sizeof(asn_DEF_RxTxTEG_tags_1)
		/sizeof(asn_DEF_RxTxTEG_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RxTxTEG_1,
	3,	/* Elements count */
	&asn_SPC_RxTxTEG_specs_1	/* Additional specs */
};

