/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18/NRPPA-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_TimeWindowDurationSRS_H_
#define	_TimeWindowDurationSRS_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TimeWindowDurationSRS_PR {
	TimeWindowDurationSRS_PR_NOTHING,	/* No components present */
	TimeWindowDurationSRS_PR_durationSymbols,
	TimeWindowDurationSRS_PR_durationSlots,
	TimeWindowDurationSRS_PR_choice_extension
} TimeWindowDurationSRS_PR;
typedef enum TimeWindowDurationSRS__durationSymbols {
	TimeWindowDurationSRS__durationSymbols_n1	= 0,
	TimeWindowDurationSRS__durationSymbols_n2	= 1,
	TimeWindowDurationSRS__durationSymbols_n4	= 2,
	TimeWindowDurationSRS__durationSymbols_n8	= 3,
	TimeWindowDurationSRS__durationSymbols_n12	= 4
	/*
	 * Enumeration is extensible
	 */
} e_TimeWindowDurationSRS__durationSymbols;
typedef enum TimeWindowDurationSRS__durationSlots {
	TimeWindowDurationSRS__durationSlots_n1	= 0,
	TimeWindowDurationSRS__durationSlots_n2	= 1,
	TimeWindowDurationSRS__durationSlots_n4	= 2,
	TimeWindowDurationSRS__durationSlots_n6	= 3,
	TimeWindowDurationSRS__durationSlots_n8	= 4,
	TimeWindowDurationSRS__durationSlots_n12	= 5,
	TimeWindowDurationSRS__durationSlots_n16	= 6
	/*
	 * Enumeration is extensible
	 */
} e_TimeWindowDurationSRS__durationSlots;

/* Forward declarations */
struct ProtocolIE_Single_Container;

/* TimeWindowDurationSRS */
typedef struct TimeWindowDurationSRS {
	TimeWindowDurationSRS_PR present;
	union TimeWindowDurationSRS_u {
		long	 durationSymbols;
		long	 durationSlots;
		struct ProtocolIE_Single_Container	*choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TimeWindowDurationSRS_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_durationSymbols_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_durationSlots_9;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_TimeWindowDurationSRS;
extern asn_CHOICE_specifics_t asn_SPC_TimeWindowDurationSRS_specs_1;
extern asn_TYPE_member_t asn_MBR_TimeWindowDurationSRS_1[3];
extern asn_per_constraints_t asn_PER_type_TimeWindowDurationSRS_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _TimeWindowDurationSRS_H_ */
#include <asn_internal.h>
