/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18/NRPPA-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_UARFCN_H_
#define	_UARFCN_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UARFCN */
typedef long	 UARFCN_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_UARFCN_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_UARFCN;
asn_struct_free_f UARFCN_free;
asn_struct_print_f UARFCN_print;
asn_constr_check_f UARFCN_constraint;
per_type_decoder_f UARFCN_decode_aper;
per_type_encoder_f UARFCN_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _UARFCN_H_ */
#include <asn_internal.h>
