/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18/NRPPA-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_UE_TEG_Info_Request_H_
#define	_UE_TEG_Info_Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UE_TEG_Info_Request {
	UE_TEG_Info_Request_onDemand	= 0,
	UE_TEG_Info_Request_periodic	= 1,
	UE_TEG_Info_Request_stop	= 2
	/*
	 * Enumeration is extensible
	 */
} e_UE_TEG_Info_Request;

/* UE-TEG-Info-Request */
typedef long	 UE_TEG_Info_Request_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_UE_TEG_Info_Request_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_UE_TEG_Info_Request;
extern const asn_INTEGER_specifics_t asn_SPC_UE_TEG_Info_Request_specs_1;
asn_struct_free_f UE_TEG_Info_Request_free;
asn_struct_print_f UE_TEG_Info_Request_print;
asn_constr_check_f UE_TEG_Info_Request_constraint;
per_type_decoder_f UE_TEG_Info_Request_decode_aper;
per_type_encoder_f UE_TEG_Info_Request_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _UE_TEG_Info_Request_H_ */
#include <asn_internal.h>
