/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18/NRPPA-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_UETxTEGAssociationItem_H_
#define	_UETxTEGAssociationItem_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "PosSRSResourceID-List.h"
#include "TimeStamp.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CarrierFreq;
struct ProtocolExtensionContainer;

/* UETxTEGAssociationItem */
typedef struct UETxTEGAssociationItem {
	long	 uE_Tx_TEG_ID;
	PosSRSResourceID_List_t	 posSRSResourceID_List;
	TimeStamp_t	 timeStamp;
	struct CarrierFreq	*carrierFreq;	/* OPTIONAL */
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UETxTEGAssociationItem_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UETxTEGAssociationItem;
extern asn_SEQUENCE_specifics_t asn_SPC_UETxTEGAssociationItem_specs_1;
extern asn_TYPE_member_t asn_MBR_UETxTEGAssociationItem_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _UETxTEGAssociationItem_H_ */
#include <asn_internal.h>
