/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18/NRPPA-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_ULRTOAMeas_H_
#define	_ULRTOAMeas_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ULRTOAMeas_PR {
	ULRTOAMeas_PR_NOTHING,	/* No components present */
	ULRTOAMeas_PR_k0,
	ULRTOAMeas_PR_k1,
	ULRTOAMeas_PR_k2,
	ULRTOAMeas_PR_k3,
	ULRTOAMeas_PR_k4,
	ULRTOAMeas_PR_k5,
	ULRTOAMeas_PR_choice_extension
} ULRTOAMeas_PR;

/* Forward declarations */
struct ProtocolIE_Single_Container;

/* ULRTOAMeas */
typedef struct ULRTOAMeas {
	ULRTOAMeas_PR present;
	union ULRTOAMeas_u {
		long	 k0;
		long	 k1;
		long	 k2;
		long	 k3;
		long	 k4;
		long	 k5;
		struct ProtocolIE_Single_Container	*choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ULRTOAMeas_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ULRTOAMeas;
extern asn_CHOICE_specifics_t asn_SPC_ULRTOAMeas_specs_1;
extern asn_TYPE_member_t asn_MBR_ULRTOAMeas_1[7];
extern asn_per_constraints_t asn_PER_type_ULRTOAMeas_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ULRTOAMeas_H_ */
#include <asn_internal.h>
