/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r18/NRPPA-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_Uncertainty_range_AoA_H_
#define	_Uncertainty_range_AoA_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Uncertainty-range-AoA */
typedef long	 Uncertainty_range_AoA_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Uncertainty_range_AoA_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Uncertainty_range_AoA;
asn_struct_free_f Uncertainty_range_AoA_free;
asn_struct_print_f Uncertainty_range_AoA_print;
asn_constr_check_f Uncertainty_range_AoA_constraint;
per_type_decoder_f Uncertainty_range_AoA_decode_aper;
per_type_encoder_f Uncertainty_range_AoA_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Uncertainty_range_AoA_H_ */
#include <asn_internal.h>
