/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SBC-AP-Containers"
 * 	found in "../support/sbcap-r16/sbcap-r16.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_SBCAP_ProtocolExtensionField_H_
#define	_SBCAP_ProtocolExtensionField_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SBCAP_ProtocolExtensionID.h"
#include "SBCAP_Criticality.h"
#include <ANY.h>
#include <asn_ioc.h>
#include "SBCAP_List-of-5GS-TAIs.h"
#include "SBCAP_Presence.h"
#include "SBCAP_Warning-Area-List-5GS.h"
#include "SBCAP_Global-RAN-Node-ID.h"
#include "SBCAP_RAT-Selector-5GS.h"
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>
#include "SBCAP_Unknown-5GS-Tracking-Area-List.h"
#include "SBCAP_Broadcast-Scheduled-Area-List-5GS.h"
#include "SBCAP_Broadcast-Cancelled-Area-List-5GS.h"
#include "SBCAP_Broadcast-Empty-Area-List-5GS.h"
#include "SBCAP_Restarted-Cell-List-NR.h"
#include "SBCAP_List-of-5GS-TAI-for-Restart.h"
#include "SBCAP_Global-GNB-ID.h"
#include "SBCAP_Failed-Cell-List-NR.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SBCAP_Write_Replace_Warning_Request_Extensions__extensionValue_PR {
	SBCAP_Write_Replace_Warning_Request_Extensions__extensionValue_PR_NOTHING,	/* No components present */
	SBCAP_Write_Replace_Warning_Request_Extensions__extensionValue_PR_List_of_5GS_TAIs,
	SBCAP_Write_Replace_Warning_Request_Extensions__extensionValue_PR_Warning_Area_List_5GS,
	SBCAP_Write_Replace_Warning_Request_Extensions__extensionValue_PR_Global_RAN_Node_ID,
	SBCAP_Write_Replace_Warning_Request_Extensions__extensionValue_PR_RAT_Selector_5GS
} SBCAP_Write_Replace_Warning_Request_Extensions__extensionValue_PR;
typedef enum SBCAP_Write_Replace_Warning_Response_Extensions__extensionValue_PR {
	SBCAP_Write_Replace_Warning_Response_Extensions__extensionValue_PR_NOTHING,	/* No components present */
	SBCAP_Write_Replace_Warning_Response_Extensions__extensionValue_PR_Unknown_5GS_Tracking_Area_List
} SBCAP_Write_Replace_Warning_Response_Extensions__extensionValue_PR;
typedef enum SBCAP_Stop_Warning_Request_Extensions__extensionValue_PR {
	SBCAP_Stop_Warning_Request_Extensions__extensionValue_PR_NOTHING,	/* No components present */
	SBCAP_Stop_Warning_Request_Extensions__extensionValue_PR_List_of_5GS_TAIs,
	SBCAP_Stop_Warning_Request_Extensions__extensionValue_PR_Warning_Area_List_5GS,
	SBCAP_Stop_Warning_Request_Extensions__extensionValue_PR_RAT_Selector_5GS
} SBCAP_Stop_Warning_Request_Extensions__extensionValue_PR;
typedef enum SBCAP_Stop_Warning_Response_Extensions__extensionValue_PR {
	SBCAP_Stop_Warning_Response_Extensions__extensionValue_PR_NOTHING,	/* No components present */
	SBCAP_Stop_Warning_Response_Extensions__extensionValue_PR_Unknown_5GS_Tracking_Area_List
} SBCAP_Stop_Warning_Response_Extensions__extensionValue_PR;
typedef enum SBCAP_Write_Replace_Warning_Indication_Extensions__extensionValue_PR {
	SBCAP_Write_Replace_Warning_Indication_Extensions__extensionValue_PR_NOTHING,	/* No components present */
	SBCAP_Write_Replace_Warning_Indication_Extensions__extensionValue_PR_Broadcast_Scheduled_Area_List_5GS
} SBCAP_Write_Replace_Warning_Indication_Extensions__extensionValue_PR;
typedef enum SBCAP_Stop_Warning_Indication_Extensions__extensionValue_PR {
	SBCAP_Stop_Warning_Indication_Extensions__extensionValue_PR_NOTHING,	/* No components present */
	SBCAP_Stop_Warning_Indication_Extensions__extensionValue_PR_Broadcast_Cancelled_Area_List_5GS,
	SBCAP_Stop_Warning_Indication_Extensions__extensionValue_PR_Broadcast_Empty_Area_List_5GS
} SBCAP_Stop_Warning_Indication_Extensions__extensionValue_PR;
typedef enum SBCAP_PWS_Restart_Indication_Extensions__extensionValue_PR {
	SBCAP_PWS_Restart_Indication_Extensions__extensionValue_PR_NOTHING,	/* No components present */
	SBCAP_PWS_Restart_Indication_Extensions__extensionValue_PR_Restarted_Cell_List_NR,
	SBCAP_PWS_Restart_Indication_Extensions__extensionValue_PR_List_of_5GS_TAI_for_Restart,
	SBCAP_PWS_Restart_Indication_Extensions__extensionValue_PR_Global_GNB_ID
} SBCAP_PWS_Restart_Indication_Extensions__extensionValue_PR;
typedef enum SBCAP_PWS_Failure_Indication_Extensions__extensionValue_PR {
	SBCAP_PWS_Failure_Indication_Extensions__extensionValue_PR_NOTHING,	/* No components present */
	SBCAP_PWS_Failure_Indication_Extensions__extensionValue_PR_Failed_Cell_List_NR,
	SBCAP_PWS_Failure_Indication_Extensions__extensionValue_PR_Global_GNB_ID
} SBCAP_PWS_Failure_Indication_Extensions__extensionValue_PR;
typedef enum SBCAP_Broadcast_Scheduled_Area_List_ExtIEs__extensionValue_PR {
	SBCAP_Broadcast_Scheduled_Area_List_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBCAP_Broadcast_Scheduled_Area_List_ExtIEs__extensionValue_PR;
typedef enum SBCAP_Broadcast_Scheduled_Area_List_5GS_ExtIEs__extensionValue_PR {
	SBCAP_Broadcast_Scheduled_Area_List_5GS_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBCAP_Broadcast_Scheduled_Area_List_5GS_ExtIEs__extensionValue_PR;
typedef enum SBCAP_Broadcast_Cancelled_Area_List_ExtIEs__extensionValue_PR {
	SBCAP_Broadcast_Cancelled_Area_List_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBCAP_Broadcast_Cancelled_Area_List_ExtIEs__extensionValue_PR;
typedef enum SBCAP_Broadcast_Cancelled_Area_List_5GS_ExtIEs__extensionValue_PR {
	SBCAP_Broadcast_Cancelled_Area_List_5GS_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBCAP_Broadcast_Cancelled_Area_List_5GS_ExtIEs__extensionValue_PR;
typedef enum SBCAP_CancelledCellinEAI_Item_ExtIEs__extensionValue_PR {
	SBCAP_CancelledCellinEAI_Item_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBCAP_CancelledCellinEAI_Item_ExtIEs__extensionValue_PR;
typedef enum SBCAP_CancelledCellinTAI_Item_ExtIEs__extensionValue_PR {
	SBCAP_CancelledCellinTAI_Item_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBCAP_CancelledCellinTAI_Item_ExtIEs__extensionValue_PR;
typedef enum SBCAP_CancelledCellinTAI_5GS_ExtIEs__extensionValue_PR {
	SBCAP_CancelledCellinTAI_5GS_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBCAP_CancelledCellinTAI_5GS_ExtIEs__extensionValue_PR;
typedef enum SBCAP_CellId_Broadcast_List_Item_ExtIEs__extensionValue_PR {
	SBCAP_CellId_Broadcast_List_Item_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBCAP_CellId_Broadcast_List_Item_ExtIEs__extensionValue_PR;
typedef enum SBCAP_CellId_Broadcast_List_5GS_ExtIEs__extensionValue_PR {
	SBCAP_CellId_Broadcast_List_5GS_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBCAP_CellId_Broadcast_List_5GS_ExtIEs__extensionValue_PR;
typedef enum SBCAP_CellID_Cancelled_Item_ExtIEs__extensionValue_PR {
	SBCAP_CellID_Cancelled_Item_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBCAP_CellID_Cancelled_Item_ExtIEs__extensionValue_PR;
typedef enum SBCAP_CellID_Cancelled_5GS_ExtIEs__extensionValue_PR {
	SBCAP_CellID_Cancelled_5GS_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBCAP_CellID_Cancelled_5GS_ExtIEs__extensionValue_PR;
typedef enum SBCAP_CriticalityDiagnostics_ExtIEs__extensionValue_PR {
	SBCAP_CriticalityDiagnostics_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBCAP_CriticalityDiagnostics_ExtIEs__extensionValue_PR;
typedef enum SBCAP_CriticalityDiagnostics_IE_Item_ExtIEs__extensionValue_PR {
	SBCAP_CriticalityDiagnostics_IE_Item_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBCAP_CriticalityDiagnostics_IE_Item_ExtIEs__extensionValue_PR;
typedef enum SBCAP_EmergencyAreaID_Broadcast_List_Item_ExtIEs__extensionValue_PR {
	SBCAP_EmergencyAreaID_Broadcast_List_Item_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBCAP_EmergencyAreaID_Broadcast_List_Item_ExtIEs__extensionValue_PR;
typedef enum SBCAP_EmergencyAreaID_Cancelled_Item_ExtIEs__extensionValue_PR {
	SBCAP_EmergencyAreaID_Cancelled_Item_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBCAP_EmergencyAreaID_Cancelled_Item_ExtIEs__extensionValue_PR;
typedef enum SBCAP_EUTRAN_CGI_ExtIEs__extensionValue_PR {
	SBCAP_EUTRAN_CGI_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBCAP_EUTRAN_CGI_ExtIEs__extensionValue_PR;
typedef enum SBCAP_GlobalENB_ID_ExtIEs__extensionValue_PR {
	SBCAP_GlobalENB_ID_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBCAP_GlobalENB_ID_ExtIEs__extensionValue_PR;
typedef enum SBCAP_Global_GNB_ID_ExtIEs__extensionValue_PR {
	SBCAP_Global_GNB_ID_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBCAP_Global_GNB_ID_ExtIEs__extensionValue_PR;
typedef enum SBCAP_Global_NgENB_ID_ExtIEs__extensionValue_PR {
	SBCAP_Global_NgENB_ID_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBCAP_Global_NgENB_ID_ExtIEs__extensionValue_PR;
typedef enum SBCAP_NR_CGI_ExtIEs__extensionValue_PR {
	SBCAP_NR_CGI_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBCAP_NR_CGI_ExtIEs__extensionValue_PR;
typedef enum SBCAP_ScheduledCellinEAI_Item_ExtIEs__extensionValue_PR {
	SBCAP_ScheduledCellinEAI_Item_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBCAP_ScheduledCellinEAI_Item_ExtIEs__extensionValue_PR;
typedef enum SBCAP_ScheduledCellinTAI_Item_ExtIEs__extensionValue_PR {
	SBCAP_ScheduledCellinTAI_Item_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBCAP_ScheduledCellinTAI_Item_ExtIEs__extensionValue_PR;
typedef enum SBCAP_ScheduledCellinTAI_5GS_ExtIEs__extensionValue_PR {
	SBCAP_ScheduledCellinTAI_5GS_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBCAP_ScheduledCellinTAI_5GS_ExtIEs__extensionValue_PR;
typedef enum SBCAP_TAI_Broadcast_List_Item_ExtIEs__extensionValue_PR {
	SBCAP_TAI_Broadcast_List_Item_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBCAP_TAI_Broadcast_List_Item_ExtIEs__extensionValue_PR;
typedef enum SBCAP_TAI_Broadcast_List_5GS_ExtIEs__extensionValue_PR {
	SBCAP_TAI_Broadcast_List_5GS_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBCAP_TAI_Broadcast_List_5GS_ExtIEs__extensionValue_PR;
typedef enum SBCAP_TAI_Cancelled_List_Item_ExtIEs__extensionValue_PR {
	SBCAP_TAI_Cancelled_List_Item_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBCAP_TAI_Cancelled_List_Item_ExtIEs__extensionValue_PR;
typedef enum SBCAP_TAI_Cancelled_List_5GS_ExtIEs__extensionValue_PR {
	SBCAP_TAI_Cancelled_List_5GS_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBCAP_TAI_Cancelled_List_5GS_ExtIEs__extensionValue_PR;
typedef enum SBCAP_TAI_ExtIEs__extensionValue_PR {
	SBCAP_TAI_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBCAP_TAI_ExtIEs__extensionValue_PR;
typedef enum SBCAP_TAI_5GS_ExtIEs__extensionValue_PR {
	SBCAP_TAI_5GS_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} SBCAP_TAI_5GS_ExtIEs__extensionValue_PR;

/* SBCAP_ProtocolExtensionField */
typedef struct SBCAP_Write_Replace_Warning_Request_Extensions {
	SBCAP_ProtocolExtensionID_t	 id;
	SBCAP_Criticality_t	 criticality;
	struct SBCAP_Write_Replace_Warning_Request_Extensions__extensionValue {
		SBCAP_Write_Replace_Warning_Request_Extensions__extensionValue_PR present;
		union SBCAP_Write_Replace_Warning_Request_Extensions__SBCAP_extensionValue_u {
			SBCAP_List_of_5GS_TAIs_t	 List_of_5GS_TAIs;
			SBCAP_Warning_Area_List_5GS_t	 Warning_Area_List_5GS;
			SBCAP_Global_RAN_Node_ID_t	 Global_RAN_Node_ID;
			SBCAP_RAT_Selector_5GS_t	 RAT_Selector_5GS;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBCAP_Write_Replace_Warning_Request_Extensions_t;
typedef struct SBCAP_Write_Replace_Warning_Response_Extensions {
	SBCAP_ProtocolExtensionID_t	 id;
	SBCAP_Criticality_t	 criticality;
	struct SBCAP_Write_Replace_Warning_Response_Extensions__extensionValue {
		SBCAP_Write_Replace_Warning_Response_Extensions__extensionValue_PR present;
		union SBCAP_Write_Replace_Warning_Response_Extensions__SBCAP_extensionValue_u {
			SBCAP_Unknown_5GS_Tracking_Area_List_t	 Unknown_5GS_Tracking_Area_List;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBCAP_Write_Replace_Warning_Response_Extensions_t;
typedef struct SBCAP_Stop_Warning_Request_Extensions {
	SBCAP_ProtocolExtensionID_t	 id;
	SBCAP_Criticality_t	 criticality;
	struct SBCAP_Stop_Warning_Request_Extensions__extensionValue {
		SBCAP_Stop_Warning_Request_Extensions__extensionValue_PR present;
		union SBCAP_Stop_Warning_Request_Extensions__SBCAP_extensionValue_u {
			SBCAP_List_of_5GS_TAIs_t	 List_of_5GS_TAIs;
			SBCAP_Warning_Area_List_5GS_t	 Warning_Area_List_5GS;
			SBCAP_RAT_Selector_5GS_t	 RAT_Selector_5GS;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBCAP_Stop_Warning_Request_Extensions_t;
typedef struct SBCAP_Stop_Warning_Response_Extensions {
	SBCAP_ProtocolExtensionID_t	 id;
	SBCAP_Criticality_t	 criticality;
	struct SBCAP_Stop_Warning_Response_Extensions__extensionValue {
		SBCAP_Stop_Warning_Response_Extensions__extensionValue_PR present;
		union SBCAP_Stop_Warning_Response_Extensions__SBCAP_extensionValue_u {
			SBCAP_Unknown_5GS_Tracking_Area_List_t	 Unknown_5GS_Tracking_Area_List;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBCAP_Stop_Warning_Response_Extensions_t;
typedef struct SBCAP_Write_Replace_Warning_Indication_Extensions {
	SBCAP_ProtocolExtensionID_t	 id;
	SBCAP_Criticality_t	 criticality;
	struct SBCAP_Write_Replace_Warning_Indication_Extensions__extensionValue {
		SBCAP_Write_Replace_Warning_Indication_Extensions__extensionValue_PR present;
		union SBCAP_Write_Replace_Warning_Indication_Extensions__SBCAP_extensionValue_u {
			SBCAP_Broadcast_Scheduled_Area_List_5GS_t	 Broadcast_Scheduled_Area_List_5GS;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBCAP_Write_Replace_Warning_Indication_Extensions_t;
typedef struct SBCAP_Stop_Warning_Indication_Extensions {
	SBCAP_ProtocolExtensionID_t	 id;
	SBCAP_Criticality_t	 criticality;
	struct SBCAP_Stop_Warning_Indication_Extensions__extensionValue {
		SBCAP_Stop_Warning_Indication_Extensions__extensionValue_PR present;
		union SBCAP_Stop_Warning_Indication_Extensions__SBCAP_extensionValue_u {
			SBCAP_Broadcast_Cancelled_Area_List_5GS_t	 Broadcast_Cancelled_Area_List_5GS;
			SBCAP_Broadcast_Empty_Area_List_5GS_t	 Broadcast_Empty_Area_List_5GS;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBCAP_Stop_Warning_Indication_Extensions_t;
typedef struct SBCAP_PWS_Restart_Indication_Extensions {
	SBCAP_ProtocolExtensionID_t	 id;
	SBCAP_Criticality_t	 criticality;
	struct SBCAP_PWS_Restart_Indication_Extensions__extensionValue {
		SBCAP_PWS_Restart_Indication_Extensions__extensionValue_PR present;
		union SBCAP_PWS_Restart_Indication_Extensions__SBCAP_extensionValue_u {
			SBCAP_Restarted_Cell_List_NR_t	 Restarted_Cell_List_NR;
			SBCAP_List_of_5GS_TAI_for_Restart_t	 List_of_5GS_TAI_for_Restart;
			SBCAP_Global_GNB_ID_t	 Global_GNB_ID;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBCAP_PWS_Restart_Indication_Extensions_t;
typedef struct SBCAP_PWS_Failure_Indication_Extensions {
	SBCAP_ProtocolExtensionID_t	 id;
	SBCAP_Criticality_t	 criticality;
	struct SBCAP_PWS_Failure_Indication_Extensions__extensionValue {
		SBCAP_PWS_Failure_Indication_Extensions__extensionValue_PR present;
		union SBCAP_PWS_Failure_Indication_Extensions__SBCAP_extensionValue_u {
			SBCAP_Failed_Cell_List_NR_t	 Failed_Cell_List_NR;
			SBCAP_Global_GNB_ID_t	 Global_GNB_ID;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBCAP_PWS_Failure_Indication_Extensions_t;
typedef struct SBCAP_Broadcast_Scheduled_Area_List_ExtIEs {
	SBCAP_ProtocolExtensionID_t	 id;
	SBCAP_Criticality_t	 criticality;
	struct SBCAP_Broadcast_Scheduled_Area_List_ExtIEs__extensionValue {
		SBCAP_Broadcast_Scheduled_Area_List_ExtIEs__extensionValue_PR present;
		union SBCAP_Broadcast_Scheduled_Area_List_ExtIEs__SBCAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBCAP_Broadcast_Scheduled_Area_List_ExtIEs_t;
typedef struct SBCAP_Broadcast_Scheduled_Area_List_5GS_ExtIEs {
	SBCAP_ProtocolExtensionID_t	 id;
	SBCAP_Criticality_t	 criticality;
	struct SBCAP_Broadcast_Scheduled_Area_List_5GS_ExtIEs__extensionValue {
		SBCAP_Broadcast_Scheduled_Area_List_5GS_ExtIEs__extensionValue_PR present;
		union SBCAP_Broadcast_Scheduled_Area_List_5GS_ExtIEs__SBCAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBCAP_Broadcast_Scheduled_Area_List_5GS_ExtIEs_t;
typedef struct SBCAP_Broadcast_Cancelled_Area_List_ExtIEs {
	SBCAP_ProtocolExtensionID_t	 id;
	SBCAP_Criticality_t	 criticality;
	struct SBCAP_Broadcast_Cancelled_Area_List_ExtIEs__extensionValue {
		SBCAP_Broadcast_Cancelled_Area_List_ExtIEs__extensionValue_PR present;
		union SBCAP_Broadcast_Cancelled_Area_List_ExtIEs__SBCAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBCAP_Broadcast_Cancelled_Area_List_ExtIEs_t;
typedef struct SBCAP_Broadcast_Cancelled_Area_List_5GS_ExtIEs {
	SBCAP_ProtocolExtensionID_t	 id;
	SBCAP_Criticality_t	 criticality;
	struct SBCAP_Broadcast_Cancelled_Area_List_5GS_ExtIEs__extensionValue {
		SBCAP_Broadcast_Cancelled_Area_List_5GS_ExtIEs__extensionValue_PR present;
		union SBCAP_Broadcast_Cancelled_Area_List_5GS_ExtIEs__SBCAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBCAP_Broadcast_Cancelled_Area_List_5GS_ExtIEs_t;
typedef struct SBCAP_CancelledCellinEAI_Item_ExtIEs {
	SBCAP_ProtocolExtensionID_t	 id;
	SBCAP_Criticality_t	 criticality;
	struct SBCAP_CancelledCellinEAI_Item_ExtIEs__extensionValue {
		SBCAP_CancelledCellinEAI_Item_ExtIEs__extensionValue_PR present;
		union SBCAP_CancelledCellinEAI_Item_ExtIEs__SBCAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBCAP_CancelledCellinEAI_Item_ExtIEs_t;
typedef struct SBCAP_CancelledCellinTAI_Item_ExtIEs {
	SBCAP_ProtocolExtensionID_t	 id;
	SBCAP_Criticality_t	 criticality;
	struct SBCAP_CancelledCellinTAI_Item_ExtIEs__extensionValue {
		SBCAP_CancelledCellinTAI_Item_ExtIEs__extensionValue_PR present;
		union SBCAP_CancelledCellinTAI_Item_ExtIEs__SBCAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBCAP_CancelledCellinTAI_Item_ExtIEs_t;
typedef struct SBCAP_CancelledCellinTAI_5GS_ExtIEs {
	SBCAP_ProtocolExtensionID_t	 id;
	SBCAP_Criticality_t	 criticality;
	struct SBCAP_CancelledCellinTAI_5GS_ExtIEs__extensionValue {
		SBCAP_CancelledCellinTAI_5GS_ExtIEs__extensionValue_PR present;
		union SBCAP_CancelledCellinTAI_5GS_ExtIEs__SBCAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBCAP_CancelledCellinTAI_5GS_ExtIEs_t;
typedef struct SBCAP_CellId_Broadcast_List_Item_ExtIEs {
	SBCAP_ProtocolExtensionID_t	 id;
	SBCAP_Criticality_t	 criticality;
	struct SBCAP_CellId_Broadcast_List_Item_ExtIEs__extensionValue {
		SBCAP_CellId_Broadcast_List_Item_ExtIEs__extensionValue_PR present;
		union SBCAP_CellId_Broadcast_List_Item_ExtIEs__SBCAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBCAP_CellId_Broadcast_List_Item_ExtIEs_t;
typedef struct SBCAP_CellId_Broadcast_List_5GS_ExtIEs {
	SBCAP_ProtocolExtensionID_t	 id;
	SBCAP_Criticality_t	 criticality;
	struct SBCAP_CellId_Broadcast_List_5GS_ExtIEs__extensionValue {
		SBCAP_CellId_Broadcast_List_5GS_ExtIEs__extensionValue_PR present;
		union SBCAP_CellId_Broadcast_List_5GS_ExtIEs__SBCAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBCAP_CellId_Broadcast_List_5GS_ExtIEs_t;
typedef struct SBCAP_CellID_Cancelled_Item_ExtIEs {
	SBCAP_ProtocolExtensionID_t	 id;
	SBCAP_Criticality_t	 criticality;
	struct SBCAP_CellID_Cancelled_Item_ExtIEs__extensionValue {
		SBCAP_CellID_Cancelled_Item_ExtIEs__extensionValue_PR present;
		union SBCAP_CellID_Cancelled_Item_ExtIEs__SBCAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBCAP_CellID_Cancelled_Item_ExtIEs_t;
typedef struct SBCAP_CellID_Cancelled_5GS_ExtIEs {
	SBCAP_ProtocolExtensionID_t	 id;
	SBCAP_Criticality_t	 criticality;
	struct SBCAP_CellID_Cancelled_5GS_ExtIEs__extensionValue {
		SBCAP_CellID_Cancelled_5GS_ExtIEs__extensionValue_PR present;
		union SBCAP_CellID_Cancelled_5GS_ExtIEs__SBCAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBCAP_CellID_Cancelled_5GS_ExtIEs_t;
typedef struct SBCAP_CriticalityDiagnostics_ExtIEs {
	SBCAP_ProtocolExtensionID_t	 id;
	SBCAP_Criticality_t	 criticality;
	struct SBCAP_CriticalityDiagnostics_ExtIEs__extensionValue {
		SBCAP_CriticalityDiagnostics_ExtIEs__extensionValue_PR present;
		union SBCAP_CriticalityDiagnostics_ExtIEs__SBCAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBCAP_CriticalityDiagnostics_ExtIEs_t;
typedef struct SBCAP_CriticalityDiagnostics_IE_Item_ExtIEs {
	SBCAP_ProtocolExtensionID_t	 id;
	SBCAP_Criticality_t	 criticality;
	struct SBCAP_CriticalityDiagnostics_IE_Item_ExtIEs__extensionValue {
		SBCAP_CriticalityDiagnostics_IE_Item_ExtIEs__extensionValue_PR present;
		union SBCAP_CriticalityDiagnostics_IE_Item_ExtIEs__SBCAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBCAP_CriticalityDiagnostics_IE_Item_ExtIEs_t;
typedef struct SBCAP_EmergencyAreaID_Broadcast_List_Item_ExtIEs {
	SBCAP_ProtocolExtensionID_t	 id;
	SBCAP_Criticality_t	 criticality;
	struct SBCAP_EmergencyAreaID_Broadcast_List_Item_ExtIEs__extensionValue {
		SBCAP_EmergencyAreaID_Broadcast_List_Item_ExtIEs__extensionValue_PR present;
		union SBCAP_EmergencyAreaID_Broadcast_List_Item_ExtIEs__SBCAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBCAP_EmergencyAreaID_Broadcast_List_Item_ExtIEs_t;
typedef struct SBCAP_EmergencyAreaID_Cancelled_Item_ExtIEs {
	SBCAP_ProtocolExtensionID_t	 id;
	SBCAP_Criticality_t	 criticality;
	struct SBCAP_EmergencyAreaID_Cancelled_Item_ExtIEs__extensionValue {
		SBCAP_EmergencyAreaID_Cancelled_Item_ExtIEs__extensionValue_PR present;
		union SBCAP_EmergencyAreaID_Cancelled_Item_ExtIEs__SBCAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBCAP_EmergencyAreaID_Cancelled_Item_ExtIEs_t;
typedef struct SBCAP_EUTRAN_CGI_ExtIEs {
	SBCAP_ProtocolExtensionID_t	 id;
	SBCAP_Criticality_t	 criticality;
	struct SBCAP_EUTRAN_CGI_ExtIEs__extensionValue {
		SBCAP_EUTRAN_CGI_ExtIEs__extensionValue_PR present;
		union SBCAP_EUTRAN_CGI_ExtIEs__SBCAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBCAP_EUTRAN_CGI_ExtIEs_t;
typedef struct SBCAP_GlobalENB_ID_ExtIEs {
	SBCAP_ProtocolExtensionID_t	 id;
	SBCAP_Criticality_t	 criticality;
	struct SBCAP_GlobalENB_ID_ExtIEs__extensionValue {
		SBCAP_GlobalENB_ID_ExtIEs__extensionValue_PR present;
		union SBCAP_GlobalENB_ID_ExtIEs__SBCAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBCAP_GlobalENB_ID_ExtIEs_t;
typedef struct SBCAP_Global_GNB_ID_ExtIEs {
	SBCAP_ProtocolExtensionID_t	 id;
	SBCAP_Criticality_t	 criticality;
	struct SBCAP_Global_GNB_ID_ExtIEs__extensionValue {
		SBCAP_Global_GNB_ID_ExtIEs__extensionValue_PR present;
		union SBCAP_Global_GNB_ID_ExtIEs__SBCAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBCAP_Global_GNB_ID_ExtIEs_t;
typedef struct SBCAP_Global_NgENB_ID_ExtIEs {
	SBCAP_ProtocolExtensionID_t	 id;
	SBCAP_Criticality_t	 criticality;
	struct SBCAP_Global_NgENB_ID_ExtIEs__extensionValue {
		SBCAP_Global_NgENB_ID_ExtIEs__extensionValue_PR present;
		union SBCAP_Global_NgENB_ID_ExtIEs__SBCAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBCAP_Global_NgENB_ID_ExtIEs_t;
typedef struct SBCAP_NR_CGI_ExtIEs {
	SBCAP_ProtocolExtensionID_t	 id;
	SBCAP_Criticality_t	 criticality;
	struct SBCAP_NR_CGI_ExtIEs__extensionValue {
		SBCAP_NR_CGI_ExtIEs__extensionValue_PR present;
		union SBCAP_NR_CGI_ExtIEs__SBCAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBCAP_NR_CGI_ExtIEs_t;
typedef struct SBCAP_ScheduledCellinEAI_Item_ExtIEs {
	SBCAP_ProtocolExtensionID_t	 id;
	SBCAP_Criticality_t	 criticality;
	struct SBCAP_ScheduledCellinEAI_Item_ExtIEs__extensionValue {
		SBCAP_ScheduledCellinEAI_Item_ExtIEs__extensionValue_PR present;
		union SBCAP_ScheduledCellinEAI_Item_ExtIEs__SBCAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBCAP_ScheduledCellinEAI_Item_ExtIEs_t;
typedef struct SBCAP_ScheduledCellinTAI_Item_ExtIEs {
	SBCAP_ProtocolExtensionID_t	 id;
	SBCAP_Criticality_t	 criticality;
	struct SBCAP_ScheduledCellinTAI_Item_ExtIEs__extensionValue {
		SBCAP_ScheduledCellinTAI_Item_ExtIEs__extensionValue_PR present;
		union SBCAP_ScheduledCellinTAI_Item_ExtIEs__SBCAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBCAP_ScheduledCellinTAI_Item_ExtIEs_t;
typedef struct SBCAP_ScheduledCellinTAI_5GS_ExtIEs {
	SBCAP_ProtocolExtensionID_t	 id;
	SBCAP_Criticality_t	 criticality;
	struct SBCAP_ScheduledCellinTAI_5GS_ExtIEs__extensionValue {
		SBCAP_ScheduledCellinTAI_5GS_ExtIEs__extensionValue_PR present;
		union SBCAP_ScheduledCellinTAI_5GS_ExtIEs__SBCAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBCAP_ScheduledCellinTAI_5GS_ExtIEs_t;
typedef struct SBCAP_TAI_Broadcast_List_Item_ExtIEs {
	SBCAP_ProtocolExtensionID_t	 id;
	SBCAP_Criticality_t	 criticality;
	struct SBCAP_TAI_Broadcast_List_Item_ExtIEs__extensionValue {
		SBCAP_TAI_Broadcast_List_Item_ExtIEs__extensionValue_PR present;
		union SBCAP_TAI_Broadcast_List_Item_ExtIEs__SBCAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBCAP_TAI_Broadcast_List_Item_ExtIEs_t;
typedef struct SBCAP_TAI_Broadcast_List_5GS_ExtIEs {
	SBCAP_ProtocolExtensionID_t	 id;
	SBCAP_Criticality_t	 criticality;
	struct SBCAP_TAI_Broadcast_List_5GS_ExtIEs__extensionValue {
		SBCAP_TAI_Broadcast_List_5GS_ExtIEs__extensionValue_PR present;
		union SBCAP_TAI_Broadcast_List_5GS_ExtIEs__SBCAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBCAP_TAI_Broadcast_List_5GS_ExtIEs_t;
typedef struct SBCAP_TAI_Cancelled_List_Item_ExtIEs {
	SBCAP_ProtocolExtensionID_t	 id;
	SBCAP_Criticality_t	 criticality;
	struct SBCAP_TAI_Cancelled_List_Item_ExtIEs__extensionValue {
		SBCAP_TAI_Cancelled_List_Item_ExtIEs__extensionValue_PR present;
		union SBCAP_TAI_Cancelled_List_Item_ExtIEs__SBCAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBCAP_TAI_Cancelled_List_Item_ExtIEs_t;
typedef struct SBCAP_TAI_Cancelled_List_5GS_ExtIEs {
	SBCAP_ProtocolExtensionID_t	 id;
	SBCAP_Criticality_t	 criticality;
	struct SBCAP_TAI_Cancelled_List_5GS_ExtIEs__extensionValue {
		SBCAP_TAI_Cancelled_List_5GS_ExtIEs__extensionValue_PR present;
		union SBCAP_TAI_Cancelled_List_5GS_ExtIEs__SBCAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBCAP_TAI_Cancelled_List_5GS_ExtIEs_t;
typedef struct SBCAP_TAI_ExtIEs {
	SBCAP_ProtocolExtensionID_t	 id;
	SBCAP_Criticality_t	 criticality;
	struct SBCAP_TAI_ExtIEs__extensionValue {
		SBCAP_TAI_ExtIEs__extensionValue_PR present;
		union SBCAP_TAI_ExtIEs__SBCAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBCAP_TAI_ExtIEs_t;
typedef struct SBCAP_TAI_5GS_ExtIEs {
	SBCAP_ProtocolExtensionID_t	 id;
	SBCAP_Criticality_t	 criticality;
	struct SBCAP_TAI_5GS_ExtIEs__extensionValue {
		SBCAP_TAI_5GS_ExtIEs__extensionValue_PR present;
		union SBCAP_TAI_5GS_ExtIEs__SBCAP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBCAP_TAI_5GS_ExtIEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SBCAP_Write_Replace_Warning_Request_Extensions;
extern asn_SEQUENCE_specifics_t asn_SPC_SBCAP_Write_Replace_Warning_Request_Extensions_specs_1;
extern asn_TYPE_member_t asn_MBR_SBCAP_Write_Replace_Warning_Request_Extensions_1[3];
extern asn_TYPE_descriptor_t asn_DEF_SBCAP_Write_Replace_Warning_Response_Extensions;
extern asn_SEQUENCE_specifics_t asn_SPC_SBCAP_Write_Replace_Warning_Response_Extensions_specs_5;
extern asn_TYPE_member_t asn_MBR_SBCAP_Write_Replace_Warning_Response_Extensions_5[3];
extern asn_TYPE_descriptor_t asn_DEF_SBCAP_Stop_Warning_Request_Extensions;
extern asn_SEQUENCE_specifics_t asn_SPC_SBCAP_Stop_Warning_Request_Extensions_specs_9;
extern asn_TYPE_member_t asn_MBR_SBCAP_Stop_Warning_Request_Extensions_9[3];
extern asn_TYPE_descriptor_t asn_DEF_SBCAP_Stop_Warning_Response_Extensions;
extern asn_SEQUENCE_specifics_t asn_SPC_SBCAP_Stop_Warning_Response_Extensions_specs_13;
extern asn_TYPE_member_t asn_MBR_SBCAP_Stop_Warning_Response_Extensions_13[3];
extern asn_TYPE_descriptor_t asn_DEF_SBCAP_Write_Replace_Warning_Indication_Extensions;
extern asn_SEQUENCE_specifics_t asn_SPC_SBCAP_Write_Replace_Warning_Indication_Extensions_specs_17;
extern asn_TYPE_member_t asn_MBR_SBCAP_Write_Replace_Warning_Indication_Extensions_17[3];
extern asn_TYPE_descriptor_t asn_DEF_SBCAP_Stop_Warning_Indication_Extensions;
extern asn_SEQUENCE_specifics_t asn_SPC_SBCAP_Stop_Warning_Indication_Extensions_specs_21;
extern asn_TYPE_member_t asn_MBR_SBCAP_Stop_Warning_Indication_Extensions_21[3];
extern asn_TYPE_descriptor_t asn_DEF_SBCAP_PWS_Restart_Indication_Extensions;
extern asn_SEQUENCE_specifics_t asn_SPC_SBCAP_PWS_Restart_Indication_Extensions_specs_25;
extern asn_TYPE_member_t asn_MBR_SBCAP_PWS_Restart_Indication_Extensions_25[3];
extern asn_TYPE_descriptor_t asn_DEF_SBCAP_PWS_Failure_Indication_Extensions;
extern asn_SEQUENCE_specifics_t asn_SPC_SBCAP_PWS_Failure_Indication_Extensions_specs_29;
extern asn_TYPE_member_t asn_MBR_SBCAP_PWS_Failure_Indication_Extensions_29[3];
extern asn_TYPE_descriptor_t asn_DEF_SBCAP_Broadcast_Scheduled_Area_List_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBCAP_Broadcast_Scheduled_Area_List_ExtIEs_specs_33;
extern asn_TYPE_member_t asn_MBR_SBCAP_Broadcast_Scheduled_Area_List_ExtIEs_33[3];
extern asn_TYPE_descriptor_t asn_DEF_SBCAP_Broadcast_Scheduled_Area_List_5GS_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBCAP_Broadcast_Scheduled_Area_List_5GS_ExtIEs_specs_37;
extern asn_TYPE_member_t asn_MBR_SBCAP_Broadcast_Scheduled_Area_List_5GS_ExtIEs_37[3];
extern asn_TYPE_descriptor_t asn_DEF_SBCAP_Broadcast_Cancelled_Area_List_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBCAP_Broadcast_Cancelled_Area_List_ExtIEs_specs_41;
extern asn_TYPE_member_t asn_MBR_SBCAP_Broadcast_Cancelled_Area_List_ExtIEs_41[3];
extern asn_TYPE_descriptor_t asn_DEF_SBCAP_Broadcast_Cancelled_Area_List_5GS_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBCAP_Broadcast_Cancelled_Area_List_5GS_ExtIEs_specs_45;
extern asn_TYPE_member_t asn_MBR_SBCAP_Broadcast_Cancelled_Area_List_5GS_ExtIEs_45[3];
extern asn_TYPE_descriptor_t asn_DEF_SBCAP_CancelledCellinEAI_Item_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBCAP_CancelledCellinEAI_Item_ExtIEs_specs_49;
extern asn_TYPE_member_t asn_MBR_SBCAP_CancelledCellinEAI_Item_ExtIEs_49[3];
extern asn_TYPE_descriptor_t asn_DEF_SBCAP_CancelledCellinTAI_Item_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBCAP_CancelledCellinTAI_Item_ExtIEs_specs_53;
extern asn_TYPE_member_t asn_MBR_SBCAP_CancelledCellinTAI_Item_ExtIEs_53[3];
extern asn_TYPE_descriptor_t asn_DEF_SBCAP_CancelledCellinTAI_5GS_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBCAP_CancelledCellinTAI_5GS_ExtIEs_specs_57;
extern asn_TYPE_member_t asn_MBR_SBCAP_CancelledCellinTAI_5GS_ExtIEs_57[3];
extern asn_TYPE_descriptor_t asn_DEF_SBCAP_CellId_Broadcast_List_Item_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBCAP_CellId_Broadcast_List_Item_ExtIEs_specs_61;
extern asn_TYPE_member_t asn_MBR_SBCAP_CellId_Broadcast_List_Item_ExtIEs_61[3];
extern asn_TYPE_descriptor_t asn_DEF_SBCAP_CellId_Broadcast_List_5GS_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBCAP_CellId_Broadcast_List_5GS_ExtIEs_specs_65;
extern asn_TYPE_member_t asn_MBR_SBCAP_CellId_Broadcast_List_5GS_ExtIEs_65[3];
extern asn_TYPE_descriptor_t asn_DEF_SBCAP_CellID_Cancelled_Item_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBCAP_CellID_Cancelled_Item_ExtIEs_specs_69;
extern asn_TYPE_member_t asn_MBR_SBCAP_CellID_Cancelled_Item_ExtIEs_69[3];
extern asn_TYPE_descriptor_t asn_DEF_SBCAP_CellID_Cancelled_5GS_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBCAP_CellID_Cancelled_5GS_ExtIEs_specs_73;
extern asn_TYPE_member_t asn_MBR_SBCAP_CellID_Cancelled_5GS_ExtIEs_73[3];
extern asn_TYPE_descriptor_t asn_DEF_SBCAP_CriticalityDiagnostics_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBCAP_CriticalityDiagnostics_ExtIEs_specs_77;
extern asn_TYPE_member_t asn_MBR_SBCAP_CriticalityDiagnostics_ExtIEs_77[3];
extern asn_TYPE_descriptor_t asn_DEF_SBCAP_CriticalityDiagnostics_IE_Item_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBCAP_CriticalityDiagnostics_IE_Item_ExtIEs_specs_81;
extern asn_TYPE_member_t asn_MBR_SBCAP_CriticalityDiagnostics_IE_Item_ExtIEs_81[3];
extern asn_TYPE_descriptor_t asn_DEF_SBCAP_EmergencyAreaID_Broadcast_List_Item_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBCAP_EmergencyAreaID_Broadcast_List_Item_ExtIEs_specs_85;
extern asn_TYPE_member_t asn_MBR_SBCAP_EmergencyAreaID_Broadcast_List_Item_ExtIEs_85[3];
extern asn_TYPE_descriptor_t asn_DEF_SBCAP_EmergencyAreaID_Cancelled_Item_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBCAP_EmergencyAreaID_Cancelled_Item_ExtIEs_specs_89;
extern asn_TYPE_member_t asn_MBR_SBCAP_EmergencyAreaID_Cancelled_Item_ExtIEs_89[3];
extern asn_TYPE_descriptor_t asn_DEF_SBCAP_EUTRAN_CGI_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBCAP_EUTRAN_CGI_ExtIEs_specs_93;
extern asn_TYPE_member_t asn_MBR_SBCAP_EUTRAN_CGI_ExtIEs_93[3];
extern asn_TYPE_descriptor_t asn_DEF_SBCAP_GlobalENB_ID_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBCAP_GlobalENB_ID_ExtIEs_specs_97;
extern asn_TYPE_member_t asn_MBR_SBCAP_GlobalENB_ID_ExtIEs_97[3];
extern asn_TYPE_descriptor_t asn_DEF_SBCAP_Global_GNB_ID_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBCAP_Global_GNB_ID_ExtIEs_specs_101;
extern asn_TYPE_member_t asn_MBR_SBCAP_Global_GNB_ID_ExtIEs_101[3];
extern asn_TYPE_descriptor_t asn_DEF_SBCAP_Global_NgENB_ID_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBCAP_Global_NgENB_ID_ExtIEs_specs_105;
extern asn_TYPE_member_t asn_MBR_SBCAP_Global_NgENB_ID_ExtIEs_105[3];
extern asn_TYPE_descriptor_t asn_DEF_SBCAP_NR_CGI_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBCAP_NR_CGI_ExtIEs_specs_109;
extern asn_TYPE_member_t asn_MBR_SBCAP_NR_CGI_ExtIEs_109[3];
extern asn_TYPE_descriptor_t asn_DEF_SBCAP_ScheduledCellinEAI_Item_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBCAP_ScheduledCellinEAI_Item_ExtIEs_specs_113;
extern asn_TYPE_member_t asn_MBR_SBCAP_ScheduledCellinEAI_Item_ExtIEs_113[3];
extern asn_TYPE_descriptor_t asn_DEF_SBCAP_ScheduledCellinTAI_Item_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBCAP_ScheduledCellinTAI_Item_ExtIEs_specs_117;
extern asn_TYPE_member_t asn_MBR_SBCAP_ScheduledCellinTAI_Item_ExtIEs_117[3];
extern asn_TYPE_descriptor_t asn_DEF_SBCAP_ScheduledCellinTAI_5GS_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBCAP_ScheduledCellinTAI_5GS_ExtIEs_specs_121;
extern asn_TYPE_member_t asn_MBR_SBCAP_ScheduledCellinTAI_5GS_ExtIEs_121[3];
extern asn_TYPE_descriptor_t asn_DEF_SBCAP_TAI_Broadcast_List_Item_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBCAP_TAI_Broadcast_List_Item_ExtIEs_specs_125;
extern asn_TYPE_member_t asn_MBR_SBCAP_TAI_Broadcast_List_Item_ExtIEs_125[3];
extern asn_TYPE_descriptor_t asn_DEF_SBCAP_TAI_Broadcast_List_5GS_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBCAP_TAI_Broadcast_List_5GS_ExtIEs_specs_129;
extern asn_TYPE_member_t asn_MBR_SBCAP_TAI_Broadcast_List_5GS_ExtIEs_129[3];
extern asn_TYPE_descriptor_t asn_DEF_SBCAP_TAI_Cancelled_List_Item_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBCAP_TAI_Cancelled_List_Item_ExtIEs_specs_133;
extern asn_TYPE_member_t asn_MBR_SBCAP_TAI_Cancelled_List_Item_ExtIEs_133[3];
extern asn_TYPE_descriptor_t asn_DEF_SBCAP_TAI_Cancelled_List_5GS_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBCAP_TAI_Cancelled_List_5GS_ExtIEs_specs_137;
extern asn_TYPE_member_t asn_MBR_SBCAP_TAI_Cancelled_List_5GS_ExtIEs_137[3];
extern asn_TYPE_descriptor_t asn_DEF_SBCAP_TAI_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBCAP_TAI_ExtIEs_specs_141;
extern asn_TYPE_member_t asn_MBR_SBCAP_TAI_ExtIEs_141[3];
extern asn_TYPE_descriptor_t asn_DEF_SBCAP_TAI_5GS_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SBCAP_TAI_5GS_ExtIEs_specs_145;
extern asn_TYPE_member_t asn_MBR_SBCAP_TAI_5GS_ExtIEs_145[3];

#ifdef __cplusplus
}
#endif

#endif	/* _SBCAP_ProtocolExtensionField_H_ */
#include <asn_internal.h>
