/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SBC-AP-PDU-Descriptions"
 * 	found in "../support/sbcap-r16/sbcap-r16.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_SBCAP_SBC_AP_PDU_H_
#define	_SBCAP_SBC_AP_PDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SBCAP_SBC_AP_PDU_PR {
	SBCAP_SBC_AP_PDU_PR_NOTHING,	/* No components present */
	SBCAP_SBC_AP_PDU_PR_initiatingMessage,
	SBCAP_SBC_AP_PDU_PR_successfulOutcome,
	SBCAP_SBC_AP_PDU_PR_unsuccessfulOutcome
	/* Extensions may appear below */
	
} SBCAP_SBC_AP_PDU_PR;

/* Forward declarations */
struct SBCAP_InitiatingMessage;
struct SBCAP_SuccessfulOutcome;
struct SBCAP_UnsuccessfulOutcome;

/* SBCAP_SBC-AP-PDU */
typedef struct SBCAP_SBC_AP_PDU {
	SBCAP_SBC_AP_PDU_PR present;
	union SBCAP_SBC_AP_PDU_u {
		struct SBCAP_InitiatingMessage	*initiatingMessage;
		struct SBCAP_SuccessfulOutcome	*successfulOutcome;
		struct SBCAP_UnsuccessfulOutcome	*unsuccessfulOutcome;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBCAP_SBC_AP_PDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SBCAP_SBC_AP_PDU;

#ifdef __cplusplus
}
#endif

#endif	/* _SBCAP_SBC_AP_PDU_H_ */
#include <asn_internal.h>
